/**
 * The weekly digest as a markdown report (FR-RET-5, FR-DOG-4): decision
 * counts, gate health, volume per tool and the top deny rules. The dogfood
 * report is this report with its own title and source line.
 *
 * The report shows tool names and rule text as logged, so it stays local;
 * `card.ts` renders what is safe to share.
 */

import type { WeeklyDigest } from "./build";

type RenderOptions = Readonly<{
	/** The heading, followed by the week key. */
	title: string;
	/** One line saying where the numbers come from. */
	source: string;
}>;

const DEFAULT_OPTIONS: RenderOptions = {
	title: "Maina weekly digest",
	source:
		"Generated by `maina digest` from the gate decisions in this repository's decision log (`.maina/decisions.db`).",
};

const pct = (x: number): string => `${(x * 100).toFixed(1)}%`;

/** The digest as markdown, ending in a newline. */
export function renderDigest(
	m: WeeklyDigest,
	options: RenderOptions = DEFAULT_OPTIONS,
): string {
	const tools = Object.entries(m.byTool)
		.sort((a, b) => b[1] - a[1])
		.map(([tool, n]) => `| ${tool} | ${n} |`);
	const rules = m.topDenyRules.map((r) => `| ${r.rule} | ${r.count} |`);
	return [
		`# ${options.title} ${m.week}`,
		"",
		options.source,
		"",
		"## Decisions",
		"",
		"| verdict | count |",
		"| --- | --- |",
		`| allow | ${m.verdicts.allow} |`,
		`| ask | ${m.verdicts.ask} |`,
		`| deny | ${m.verdicts.deny} |`,
		`| **total** | ${m.total} |`,
		"",
		"## Gate health",
		"",
		`- Deny rate: ${pct(m.denyRate)}`,
		`- Ask rate: ${pct(m.askRate)}`,
		`- Overrides: ${m.overrides} (${pct(m.overrideRate)} of denies contested)`,
		`- Crashes (failed closed to ask): ${m.crashes}`,
		"",
		"## By tool",
		"",
		"| tool | count |",
		"| --- | --- |",
		...(tools.length > 0 ? tools : ["| (none) | 0 |"]),
		"",
		"## Top deny rules",
		"",
		"| rule | count |",
		"| --- | --- |",
		...(rules.length > 0 ? rules : ["| (none) | 0 |"]),
		"",
	].join("\n");
}
