import { join } from "node:path";
import { intro, isCancel, log, outro, select, text } from "@clack/prompts";
import {
	appendWorkflowStep,
	checkAIAvailability,
	consultWikiForBrainstorm,
	getCurrentBranch,
	getWorkflowId,
	recordFeedbackAsync,
} from "@mainahq/core";
import { Command } from "commander";

// ── Types ────────────────────────────────────────────────────────────────────

export interface BrainstormActionOptions {
	title?: string;
	cwd?: string;
	noInteractive?: boolean;
}

export interface BrainstormActionResult {
	created: boolean;
	issueUrl?: string;
	title?: string;
	reason?: string;
}

export interface BrainstormDeps {
	spawnGhIssue: (
		title: string,
		body: string,
		cwd: string,
	) => Promise<{ exitCode: number; stdout: string; stderr: string }>;
}

async function defaultSpawnGhIssue(
	title: string,
	body: string,
	cwd: string,
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
	const proc = Bun.spawn(
		[
			"gh",
			"issue",
			"create",
			"--title",
			title,
			"--body",
			body,
			"--label",
			"enhancement",
		],
		{ cwd, stdout: "pipe", stderr: "pipe" },
	);
	const stdout = await new Response(proc.stdout).text();
	const stderr = await new Response(proc.stderr).text();
	const exitCode = await proc.exited;
	return { exitCode, stdout, stderr };
}

const defaultDeps: BrainstormDeps = {
	spawnGhIssue: defaultSpawnGhIssue,
};

// ── Issue body generator ─────────────────────────────────────────────────────

export function generateIssueBody(
	title: string,
	userType: string,
	problem: string,
	scope: string,
): string {
	const sections: string[] = [];

	sections.push("## Problem\n");
	sections.push(problem || `[Describe the problem ${title} solves]`);

	sections.push("\n## User Stories\n");
	const user = userType || "developer";
	sections.push(
		`- As a ${user}, I want ${title.toLowerCase()} so that [benefit]`,
	);

	sections.push("\n## Acceptance Criteria\n");
	sections.push("- [ ] [Primary criterion]");
	sections.push("- [ ] [Secondary criterion]");
	sections.push("- [ ] [Edge case handled]");

	sections.push("\n## Scope\n");
	sections.push(`**Size:** ${scope || "medium"}\n`);
	sections.push("### In Scope\n");
	sections.push("- [What this includes]");
	sections.push("\n### Out of Scope\n");
	sections.push("- [What this explicitly does NOT include]");

	sections.push("\n## Edge Cases\n");
	sections.push("- [Known edge case 1]");
	sections.push("- [Known edge case 2]");

	sections.push("\n---");
	sections.push("Generated by `maina brainstorm`");

	return sections.join("\n");
}

// ── Minimal body for non-interactive mode ────────────────────────────────────

export function generateMinimalIssueBody(title: string): string {
	const sections: string[] = [];

	sections.push("## Problem\n");
	sections.push(
		`Implement ${title.toLowerCase()} to improve the developer experience.`,
	);

	sections.push("\n## Scope\n");
	sections.push(`This issue tracks the work needed to ${title.toLowerCase()}.`);

	sections.push("\n## Acceptance Criteria\n");
	sections.push("- [ ] ");

	sections.push("\n---");
	sections.push("Generated by `maina brainstorm`");

	return sections.join("\n");
}

// ── Core Action (testable) ───────────────────────────────────────────────────

export async function brainstormAction(
	options: BrainstormActionOptions,
	deps: BrainstormDeps = defaultDeps,
): Promise<BrainstormActionResult> {
	const cwd = options.cwd ?? process.cwd();
	const mainaDir = join(cwd, ".maina");

	// ── AI availability check ────────────────────────────────────────────
	const ai = checkAIAvailability();
	if (!ai.available) {
		log.error(ai.reason ?? "AI features unavailable.");
		log.message(
			"  Run `maina init` to set up AI, or run inside an AI coding agent.",
		);
		return { created: false, reason: "AI not configured" };
	}

	// ── Step 0: Load wiki context for grounding ─────────────────────────
	const wikiDir = join(cwd, ".maina", "wiki");
	const wikiContext = consultWikiForBrainstorm(wikiDir);

	if (wikiContext.moduleCount > 0 && !options.noInteractive) {
		log.info(
			`Wiki: ${wikiContext.moduleCount} modules, ${wikiContext.decisionCount} decisions`,
		);
		if (wikiContext.recentFeatures.length > 0) {
			log.message(`  Recent: ${wikiContext.recentFeatures[0]}`);
		}
	}

	// ── Step 1: Get the idea ──────────────────────────────────────────────
	let title = options.title;

	if (!title && !options.noInteractive) {
		const input = await text({
			message: "What are you building?",
			placeholder: "Describe the feature or problem in one sentence",
			validate: (v) => {
				if (!v?.trim()) return "Required";
			},
		});
		if (isCancel(input)) return { created: false, reason: "Cancelled" };
		title = input as string;
	}

	if (!title) {
		return {
			created: false,
			reason: "Title is required in non-interactive mode",
		};
	}

	// ── Step 2: Explore the idea interactively ────────────────────────────
	let userType = "";
	let problem = "";
	let scope = "";

	if (!options.noInteractive) {
		// Who is this for?
		const whoResult = await select({
			message: "Who is the primary user?",
			options: [
				{ value: "developer", label: "Developer (using maina)" },
				{ value: "team-lead", label: "Team lead (managing quality)" },
				{ value: "devops", label: "DevOps (CI/CD integration)" },
				{ value: "other", label: "Other" },
			],
		});
		if (isCancel(whoResult)) return { created: false, reason: "Cancelled" };
		userType = whoResult as string;

		// What problem does it solve?
		const problemResult = await text({
			message: "What problem does this solve?",
			placeholder: "Describe what's broken, missing, or painful",
		});
		if (isCancel(problemResult)) return { created: false, reason: "Cancelled" };
		problem = (problemResult as string) || "";

		// What's the scope?
		const scopeResult = await select({
			message: "How big is this?",
			options: [
				{ value: "small", label: "Small — single file change, <1 hour" },
				{ value: "medium", label: "Medium — multiple files, 1-4 hours" },
				{ value: "large", label: "Large — new module, 4+ hours" },
				{
					value: "epic",
					label: "Epic — multiple features, needs decomposition",
				},
			],
		});
		if (isCancel(scopeResult)) return { created: false, reason: "Cancelled" };
		scope = scopeResult as string;
	}

	// ── Step 3: Generate the issue body ──────────────────────────────────
	let body = options.noInteractive
		? generateMinimalIssueBody(title)
		: generateIssueBody(title, userType, problem, scope);

	// Append wiki architecture context if available
	if (wikiContext.architecture) {
		const wikiSection = [
			"\n## System Context (from wiki)\n",
			`Modules: ${wikiContext.moduleCount} | Decisions: ${wikiContext.decisionCount}`,
			"",
			wikiContext.recentFeatures.length > 0
				? `Recent features: ${wikiContext.recentFeatures.join(", ")}`
				: "",
		]
			.filter(Boolean)
			.join("\n");
		body += `\n${wikiSection}\n`;
	}

	// ── Step 4: Create GitHub issue ───────────────────────────────────────
	log.step("Creating GitHub issue...");

	const { exitCode, stdout, stderr } = await deps.spawnGhIssue(
		title,
		body,
		cwd,
	);

	if (exitCode !== 0) {
		const errorMsg = stderr.trim() || stdout.trim() || "gh CLI error";
		log.error(`Failed to create issue: ${errorMsg}`);
		return { created: false, reason: errorMsg };
	}

	const issueUrl = stdout.trim();
	log.success(`Issue created: ${issueUrl}`);

	// ── Step 5: Record in workflow context ────────────────────────────────
	try {
		appendWorkflowStep(
			mainaDir,
			"brainstorm",
			`Issue created: ${title}. ${issueUrl}`,
		);

		const branch = await getCurrentBranch(cwd);
		const workflowId = getWorkflowId(branch);
		recordFeedbackAsync(mainaDir, {
			promptHash: "deterministic",
			task: "brainstorm",
			accepted: true,
			timestamp: new Date().toISOString(),
			workflowStep: "brainstorm",
			workflowId,
		});
	} catch {
		// Workflow recording should never block the result
	}

	return { created: true, issueUrl, title };
}

// ── Commander Command ────────────────────────────────────────────────────────

export function brainstormCommand(): Command {
	return new Command("brainstorm")
		.description("Explore an idea and create a structured ticket")
		.option("-t, --title <title>", "Feature title (skips first question)")
		.option("--no-interactive", "Generate ticket without prompts")
		.action(async (options) => {
			intro("maina brainstorm");

			const result = await brainstormAction({
				title: options.title,
				noInteractive: options.interactive === false,
			});

			if (result.created) {
				log.info("Next steps:");
				log.message("  1. Edit the issue — fill in [brackets]");
				log.message("  2. Run `maina plan <name>` to start implementing");
				outro(`Brainstorm complete: ${result.issueUrl}`);
			} else {
				outro(`Aborted: ${result.reason}`);
			}
		});
}
