/**
 * `maina digest [--week yyyy-ww] [--send] [--card-labels] [--json]`
 * (FR-RET-5, #350): what the gate did this week, from the repository's
 * decision log (`.maina/decisions.db`), as a markdown report plus a short
 * card that is safe to share (numbers and Maina's own labels, no code,
 * paths or repository names).
 *
 * Delivery is off unless configured: only `--send` delivers, and only to
 * the channels the `digest` section of `.maina/config.json` names (an
 * https webhook, or recipients for the local `sendmail`). Only the card
 * leaves the machine.
 *
 * `--dogfood [--commit]` (#570) writes the week that just ended as the
 * dogfood report, `docs/dogfood/<yyyy-ww>.md` (what the release gate's
 * dogfood-weeks evidence reads), and with `--commit` commits that file
 * alone. The report holds counts and Maina's own labels, never commands or
 * paths, because the decision log holds only hashes and labels.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
	buildDigest,
	type DeliveryReport,
	type DigestDelivery,
	type DigestEvent,
	type DigestSubject,
	decisionLogEvents,
	deliverDigest,
	describeChannelError,
	findGateSubject,
	isoWeek,
	isWeekKey,
	loadConfig,
	type NetworkPort,
	type ProcessPort,
	type Result,
	readLogSlice,
	renderDigest,
	renderDigestCard,
	systemProcess,
	type WeekBounds,
	type WeeklyDigest,
	weekBounds,
} from "@mainahq/core";
import { Command } from "commander";
import { openDecisionDb } from "../decision-store";
import {
	EXIT_CONFIG_ERROR,
	EXIT_FINDINGS,
	EXIT_PASSED,
	EXIT_TOOL_FAILURE,
} from "../json";
import { fetchNetwork, nodeFs } from "../ports";
import { recordRetention } from "../retention";

type DigestOptions = Readonly<{
	week?: string;
	send?: boolean;
	json?: boolean;
	/** Also put tool names and deny rules on the card. */
	cardLabels?: boolean;
	/** Write the dogfood report for the week (default: the one that ended). */
	dogfood?: boolean;
	/** With `dogfood`: commit the report file, and only it. */
	commit?: boolean;
}>;

export type DigestDeps = Readonly<{
	root: string;
	now: () => number;
	/** The gate events inside `bounds`. */
	readEvents: (bounds: WeekBounds) => Result<readonly DigestEvent[], string>;
	/** The `digest` section of the config; undefined when there is none. */
	loadDelivery: () => Promise<Result<DigestDelivery | undefined, string>>;
	network: NetworkPort;
	process: ProcessPort;
	/** Writes a file, creating its directory. */
	writeFile: (path: string, content: string) => Result<void, string>;
	stdout: (text: string) => void;
	stderr: (text: string) => void;
	/**
	 * Notes a digest printed for a human in the local retention history
	 * (FR-RET-7). Never rejects; absent: nothing is noted.
	 */
	seen?: () => Promise<void>;
}>;

const META = { schemaVersion: "v1" } as const;

const OFF_HINT =
	"Delivery is off: add a `digest` section (webhook or email) to .maina/config.json to send the card.\n";

function failed(report: DeliveryReport | null): boolean {
	return report?.kind === "sent" && report.results.some((r) => !r.ok);
}

const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

/** Title and source line of the dogfood report; the title is what the release gate parses. */
export const DOGFOOD_REPORT = {
	title: "Dogfood report",
	source:
		"Generated by `maina digest --dogfood` from the gate decisions in this repository's decision log (`.maina/decisions.db`).",
} as const;

/** The dogfood report for `digest`: `docs/dogfood/<yyyy-ww>.md`'s content. */
export function renderDogfoodReport(digest: WeeklyDigest): string {
	return renderDigest(digest, DOGFOOD_REPORT);
}

/** The dogfood report's path, relative to the repository root. */
function dogfoodReportPath(week: string): string {
	return `docs/dogfood/${week}.md`;
}

type CommitResult = Result<"committed" | "unchanged", string>;

/** `git add` the report, then commit it alone unless it is unchanged. */
async function commitReport(
	path: string,
	week: string,
	deps: DigestDeps,
): Promise<CommitResult> {
	const git = async (
		args: readonly string[],
	): Promise<Result<number, string>> => {
		const r = await deps.process.spawn(["git", ...args], { cwd: deps.root });
		if (!r.ok) {
			return {
				ok: false,
				error: `git ${args[0]}: ${r.error.kind === "timeout" ? "timed out" : r.error.message}`,
			};
		}
		return { ok: true, value: r.value.exitCode };
	};
	const failure = (args: readonly string[], code: number): CommitResult => ({
		ok: false,
		error: `git ${args[0]} failed (exit ${code})`,
	});
	const add = ["add", "--", path];
	const added = await git(add);
	if (!added.ok) return added;
	if (added.value !== 0) return failure(add, added.value);
	const diff = ["diff", "--cached", "--quiet", "--", path];
	const changed = await git(diff);
	if (!changed.ok) return changed;
	if (changed.value === 0) return { ok: true, value: "unchanged" };
	if (changed.value !== 1) return failure(diff, changed.value);
	const commit = [
		"commit",
		"-m",
		`docs: weekly dogfood report ${week}`,
		"--",
		path,
	];
	const committed = await git(commit);
	if (!committed.ok) return committed;
	return committed.value === 0
		? { ok: true, value: "committed" }
		: failure(commit, committed.value);
}

/** Runs `maina digest`; resolves to the exit code. Never rejects. */
export async function runDigest(
	options: DigestOptions,
	deps: DigestDeps,
): Promise<number> {
	const fail = (code: string, message: string, exit: number): number => {
		if (options.json) {
			deps.stdout(
				`${JSON.stringify({ data: null, error: { code, message }, meta: META }, null, 2)}\n`,
			);
		} else {
			deps.stderr(`maina digest: ${message}\n`);
		}
		return exit;
	};

	if (options.commit && !options.dogfood) {
		return fail(
			"invalid_flags",
			"--commit needs --dogfood (it commits the dogfood report)",
			EXIT_CONFIG_ERROR,
		);
	}
	if (options.dogfood && options.send) {
		return fail(
			"invalid_flags",
			"--dogfood writes the report and delivers nothing; run --send on its own",
			EXIT_CONFIG_ERROR,
		);
	}
	const week =
		options.week ??
		isoWeek(options.dogfood ? deps.now() - WEEK_MS : deps.now());
	if (!isWeekKey(week)) {
		return fail(
			"invalid_week",
			`invalid week "${week}"; expected yyyy-ww (e.g. ${isoWeek(deps.now())})`,
			EXIT_CONFIG_ERROR,
		);
	}
	const events = deps.readEvents(weekBounds(week));
	if (!events.ok) {
		return fail(
			"decision_log",
			`cannot read the decision log: ${events.error}`,
			EXIT_TOOL_FAILURE,
		);
	}
	const digest = buildDigest(events.value, week);
	if (options.dogfood) {
		return writeDogfoodReport(week, digest, options, deps, fail);
	}
	const card = renderDigestCard(digest, {
		includeLabels: options.cardLabels === true,
	});

	let delivery: DeliveryReport | null = null;
	if (options.send) {
		const loaded = await deps.loadDelivery();
		if (!loaded.ok) return fail("config", loaded.error, EXIT_CONFIG_ERROR);
		delivery = await deliverDigest({ week, card }, loaded.value, deps);
	}
	const exit = failed(delivery) ? EXIT_TOOL_FAILURE : EXIT_PASSED;

	if (options.json) {
		deps.stdout(
			`${JSON.stringify({ data: { week, digest, card, delivery }, error: null, meta: META }, null, 2)}\n`,
		);
		return exit;
	}
	await deps.seen?.();
	deps.stdout(
		`${renderDigest(digest)}\n---\n\nShareable card${options.cardLabels ? " (with tool names and rules)" : " (no code, paths or repo names)"}:\n\n${card}\n`,
	);
	if (delivery?.kind === "off") deps.stdout(`\n${OFF_HINT}`);
	if (delivery?.kind === "sent") {
		for (const r of delivery.results) {
			if (r.ok) deps.stdout(`\nSent to ${r.channel}.\n`);
			else
				deps.stderr(`maina digest: ${r.channel}: ${describeChannelError(r)}\n`);
		}
	}
	return exit;
}

/** `--dogfood [--commit]`: writes (and commits) the week's dogfood report. */
async function writeDogfoodReport(
	week: string,
	digest: WeeklyDigest,
	options: DigestOptions,
	deps: DigestDeps,
	fail: (code: string, message: string, exit: number) => number,
): Promise<number> {
	const path = dogfoodReportPath(week);
	const written = deps.writeFile(
		join(deps.root, path),
		renderDogfoodReport(digest),
	);
	if (!written.ok) {
		return fail(
			"write",
			`cannot write ${path}: ${written.error}`,
			EXIT_TOOL_FAILURE,
		);
	}
	let committed: "committed" | "unchanged" | null = null;
	if (options.commit) {
		if (digest.total === 0) {
			return fail(
				"empty_week",
				`no gate decisions in ${week}: wrote ${path} but did not commit it (a week without decisions does not count as a dogfood week; run this where the dogfood hook logs to .maina/decisions.db)`,
				EXIT_FINDINGS,
			);
		}
		const r = await commitReport(path, week, deps);
		if (!r.ok) {
			return fail(
				"commit",
				`cannot commit ${path}: ${r.error}`,
				EXIT_TOOL_FAILURE,
			);
		}
		committed = r.value;
	}
	if (options.json) {
		deps.stdout(
			`${JSON.stringify({ data: { week, digest, report: { path, committed } }, error: null, meta: META }, null, 2)}\n`,
		);
		return EXIT_PASSED;
	}
	deps.stdout(`Wrote ${path} (${digest.total} gate decisions)\n`);
	if (committed === "committed") deps.stdout(`Committed ${path}.\n`);
	if (committed === "unchanged") {
		deps.stdout(`${path} is already committed; nothing to commit.\n`);
	}
	if (digest.total === 0) {
		deps.stderr(
			`maina digest: no gate decisions in ${week}; this report does not count as a dogfood week.\n`,
		);
	}
	return EXIT_PASSED;
}

function describeLogError(error: object): string {
	const kind = "kind" in error ? String(error.kind) : "error";
	return "message" in error ? `${kind}: ${String(error.message)}` : kind;
}

/**
 * The gate events of `mainaDir`'s decision log inside `bounds`. A
 * repository without a log has an empty week; none is created.
 */
export function readDecisionEvents(
	mainaDir: string,
	bounds: WeekBounds,
): Result<readonly DigestEvent[], string> {
	if (!existsSync(join(mainaDir, "decisions.db"))) {
		return { ok: true, value: [] };
	}
	const store = openDecisionDb(mainaDir);
	if (!store.ok) return store;
	const { db, close } = store.value;
	try {
		const slice = readLogSlice(
			{ db },
			{ type: "action.risk", since: bounds.since, until: bounds.until },
		);
		if (!slice.ok) return { ok: false, error: describeLogError(slice.error) };
		const subjects = new Map<string, DigestSubject>();
		for (const { id } of slice.value.decisions) {
			const found = findGateSubject(db, id);
			// A missing or unreadable subject leaves that event "unknown".
			if (found.ok && found.value !== undefined) subjects.set(id, found.value);
		}
		return { ok: true, value: decisionLogEvents(slice.value, subjects) };
	} finally {
		close();
	}
}

export function digestCommand(): Command {
	return new Command("digest")
		.description(
			"Weekly gate digest from the decision log, with a card that is safe to share",
		)
		.option(
			"--week <yyyy-ww>",
			"ISO week to digest (default: this week; with --dogfood, the week that just ended)",
		)
		.option(
			"--send",
			"deliver the card to the channels in .maina/config.json `digest` (off unless configured)",
		)
		.option(
			"--card-labels",
			"also put tool names and deny rules on the card (they can name files or repos)",
		)
		.option(
			"--dogfood",
			"write the dogfood report docs/dogfood/<yyyy-ww>.md (default week: the one that just ended)",
		)
		.option("--commit", "with --dogfood: commit the report file, and only it")
		.option("--json", "emit a { data, error, meta } envelope")
		.action(async (opts: DigestOptions) => {
			const root = process.cwd();
			process.exitCode = await runDigest(opts, {
				root,
				now: () => Date.now(),
				readEvents: (bounds) =>
					readDecisionEvents(join(root, ".maina"), bounds),
				loadDelivery: async () => {
					const config = await loadConfig({ fs: nodeFs }, root);
					return config.ok
						? { ok: true, value: config.value.digest }
						: {
								ok: false,
								error: config.error
									.map(
										(e) =>
											`${e.file}${e.path ? ` ${e.path}` : ""}: ${e.message}`,
									)
									.join("; "),
							};
				},
				network: fetchNetwork,
				process: systemProcess,
				writeFile: (path, content) => {
					try {
						mkdirSync(dirname(path), { recursive: true });
						writeFileSync(path, content, "utf-8");
						return { ok: true, value: undefined };
					} catch (e) {
						return {
							ok: false,
							error: e instanceof Error ? e.message : String(e),
						};
					}
				},
				stdout: (text) => process.stdout.write(text),
				stderr: (text) => process.stderr.write(text),
				seen: () =>
					recordRetention({
						kind: "surface",
						ts: Date.now(),
						surface: "digest",
					}),
			});
		});
}
