/**
 * The digest's markdown report (#350). The dogfood report is this renderer
 * with its own title and source line; its golden files were captured from
 * `scripts/dogfood/report.ts` before the move, so any byte that changes here
 * changes the dogfood report too.
 */

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildDigest, gateLogEvents, parseGateLog } from "../build";
import { renderDigest } from "../render";

const FIXTURES = join(import.meta.dir, "fixtures");
const read = (name: string): string =>
	readFileSync(join(FIXTURES, name), "utf-8");

const DOGFOOD = {
	title: "Dogfood report",
	source:
		"Generated by `bun run dogfood:report` from the dogfood PreToolUse hook log (`.maina/dogfood/log.jsonl`).",
};

const events = gateLogEvents(parseGateLog(read("gate-log.jsonl")).records);

describe("renderDigest (golden: the dogfood report before the move)", () => {
	test.each([
		"2026-39",
		"2026-40",
	])("week %s renders byte-for-byte as before", (week) => {
		expect(renderDigest(buildDigest(events, week), DOGFOOD)).toBe(
			read(`dogfood-report-${week}.md`),
		);
	});
});

describe("renderDigest defaults", () => {
	test("titles the report as the weekly digest", () => {
		const md = renderDigest(buildDigest(events, "2026-39"));
		expect(md.startsWith("# Maina weekly digest 2026-39\n")).toBe(true);
		expect(md).toContain("`maina digest`");
		expect(md).toContain("| deny | 4 |");
	});

	test("an empty week still renders every section", () => {
		const md = renderDigest(buildDigest([], "2026-10"));
		expect(md).toContain("| **total** | 0 |");
		expect(md).toContain("| (none) | 0 |");
		expect(md).toContain("- Deny rate: 0.0%");
	});
});
