import {
	afterAll,
	afterEach,
	beforeEach,
	describe,
	expect,
	mock,
	test,
} from "bun:test";
import { mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";

// ── Mock State ───────────────────────────────────────────────────────────────

let mockTextResponses: string[] = [];
let mockTextCallIndex = 0;
let mockSelectResponses: string[] = [];
let mockSelectCallIndex = 0;

// ── Mocks ────────────────────────────────────────────────────────────────────

mock.module("@clack/prompts", () => ({
	intro: () => {},
	outro: () => {},
	log: {
		info: () => {},
		error: () => {},
		warning: () => {},
		success: () => {},
		message: () => {},
		step: () => {},
	},
	spinner: () => ({ start: () => {}, stop: () => {} }),
	text: async () => {
		const response = mockTextResponses[mockTextCallIndex] ?? "";
		mockTextCallIndex++;
		return response;
	},
	select: async () => {
		const response = mockSelectResponses[mockSelectCallIndex] ?? "developer";
		mockSelectCallIndex++;
		return response;
	},
	isCancel: (v: unknown) => typeof v === "symbol",
}));

mock.module("@mainahq/core", () => ({
	appendWorkflowStep: () => {},
	getCurrentBranch: async () => "feature/022-brainstorm-command",
	getWorkflowId: () => "wf-022",
	recordFeedbackAsync: () => {},
}));

afterAll(() => {
	mock.restore();
});

// ── Import the module under test AFTER mocks ─────────────────────────────────

const { brainstormAction, generateIssueBody } = await import("../brainstorm");
type BrainstormDepsType = import("../brainstorm").BrainstormDeps;

// ── Helpers ───────────────────────────────────────────────────────────────────

let tmpDir: string;

beforeEach(() => {
	tmpDir = join(
		import.meta.dir,
		`tmp-brainstorm-${Date.now()}-${Math.random().toString(36).slice(2)}`,
	);
	mkdirSync(tmpDir, { recursive: true });

	mockTextResponses = [];
	mockTextCallIndex = 0;
	mockSelectResponses = [];
	mockSelectCallIndex = 0;
});

afterEach(() => {
	try {
		rmSync(tmpDir, { recursive: true, force: true });
	} catch {
		// ignore
	}
});

function makeDeps(override?: Partial<BrainstormDepsType>): BrainstormDepsType {
	return {
		spawnGhIssue: async () => ({
			exitCode: 0,
			stdout: "https://github.com/owner/repo/issues/42",
			stderr: "",
		}),
		...override,
	};
}

// ── generateIssueBody ─────────────────────────────────────────────────────────

describe("generateIssueBody", () => {
	test("includes title in user story", () => {
		const body = generateIssueBody("add dark mode", "developer", "", "small");
		expect(body).toContain("add dark mode");
		expect(body).toContain("As a developer");
	});

	test("includes problem when provided", () => {
		const body = generateIssueBody(
			"add dark mode",
			"developer",
			"Eyes hurt at night",
			"small",
		);
		expect(body).toContain("Eyes hurt at night");
	});

	test("uses placeholder problem when empty", () => {
		const body = generateIssueBody("my feature", "", "", "");
		expect(body).toContain("[Describe the problem");
	});

	test("includes scope size", () => {
		const body = generateIssueBody("thing", "team-lead", "reason", "epic");
		expect(body).toContain("**Size:** epic");
	});

	test("includes acceptance criteria checklist", () => {
		const body = generateIssueBody("thing", "developer", "", "medium");
		expect(body).toContain("- [ ]");
	});

	test("includes edge cases section", () => {
		const body = generateIssueBody("thing", "developer", "", "medium");
		expect(body).toContain("## Edge Cases");
	});

	test("includes generated-by footer", () => {
		const body = generateIssueBody("thing", "developer", "", "medium");
		expect(body).toContain("Generated by `maina brainstorm`");
	});

	test("includes in scope and out of scope sections", () => {
		const body = generateIssueBody("thing", "developer", "", "medium");
		expect(body).toContain("### In Scope");
		expect(body).toContain("### Out of Scope");
	});
});

// ── brainstormAction ──────────────────────────────────────────────────────────

describe("brainstormAction", () => {
	test("creates issue with --title flag (non-interactive)", async () => {
		let capturedTitle = "";
		let capturedBody = "";

		const deps = makeDeps({
			spawnGhIssue: async (title, body) => {
				capturedTitle = title;
				capturedBody = body;
				return {
					exitCode: 0,
					stdout: "https://github.com/owner/repo/issues/1",
					stderr: "",
				};
			},
		});

		const result = await brainstormAction(
			{ title: "Add dark mode", noInteractive: true, cwd: tmpDir },
			deps,
		);

		expect(result.created).toBe(true);
		expect(result.issueUrl).toBe("https://github.com/owner/repo/issues/1");
		expect(result.title).toBe("Add dark mode");
		expect(capturedTitle).toBe("Add dark mode");
		expect(capturedBody).toContain("add dark mode");
	});

	test("returns created:false with reason when no title in non-interactive mode", async () => {
		const deps = makeDeps();
		const result = await brainstormAction(
			{ noInteractive: true, cwd: tmpDir },
			deps,
		);
		expect(result.created).toBe(false);
		expect(result.reason).toBe("No title provided");
	});

	test("prompts for title in interactive mode", async () => {
		mockTextResponses = ["Interactive Feature"];
		mockSelectResponses = ["developer", "medium"];

		let capturedTitle = "";
		const deps = makeDeps({
			spawnGhIssue: async (title) => {
				capturedTitle = title;
				return {
					exitCode: 0,
					stdout: "https://github.com/owner/repo/issues/5",
					stderr: "",
				};
			},
		});

		const result = await brainstormAction({ cwd: tmpDir }, deps);

		expect(result.created).toBe(true);
		expect(capturedTitle).toBe("Interactive Feature");
	});

	test("returns created:false when gh exits non-zero", async () => {
		const deps = makeDeps({
			spawnGhIssue: async () => ({
				exitCode: 1,
				stdout: "",
				stderr: "Authentication required",
			}),
		});

		const result = await brainstormAction(
			{ title: "Test feature", noInteractive: true, cwd: tmpDir },
			deps,
		);

		expect(result.created).toBe(false);
		expect(result.reason).toContain("Authentication required");
	});

	test("returns created:false with stdout error when stderr is empty", async () => {
		const deps = makeDeps({
			spawnGhIssue: async () => ({
				exitCode: 1,
				stdout: "gh: not logged in",
				stderr: "",
			}),
		});

		const result = await brainstormAction(
			{ title: "Test feature", noInteractive: true, cwd: tmpDir },
			deps,
		);

		expect(result.created).toBe(false);
		expect(result.reason).toContain("gh: not logged in");
	});

	test("includes label=enhancement in gh call", async () => {
		// Verify enhancement label gets passed — captured via body content check
		let capturedArgs = "";
		const deps = makeDeps({
			spawnGhIssue: async (title, body) => {
				capturedArgs = `${title}|${body}`;
				return {
					exitCode: 0,
					stdout: "https://github.com/owner/repo/issues/7",
					stderr: "",
				};
			},
		});

		const result = await brainstormAction(
			{ title: "My feature", noInteractive: true, cwd: tmpDir },
			deps,
		);

		expect(result.created).toBe(true);
		// The title and body are forwarded to gh
		expect(capturedArgs).toContain("My feature");
	});

	test("interactive: uses select responses for userType and scope", async () => {
		mockTextResponses = ["New Feature Title", "Solve a big pain"];
		mockSelectResponses = ["team-lead", "large"];

		let capturedBody = "";
		const deps = makeDeps({
			spawnGhIssue: async (_title, body) => {
				capturedBody = body;
				return {
					exitCode: 0,
					stdout: "https://github.com/owner/repo/issues/9",
					stderr: "",
				};
			},
		});

		const result = await brainstormAction({ cwd: tmpDir }, deps);

		expect(result.created).toBe(true);
		expect(capturedBody).toContain("As a team-lead");
		expect(capturedBody).toContain("**Size:** large");
		expect(capturedBody).toContain("Solve a big pain");
	});
});
