/**
 * Tests for the weekly dogfood report (#286, FR-DOG-4; #570).
 *
 * The report reads one ISO week of gate decisions from the decision log
 * (`.maina/decisions.db`, which the dogfood hook's runtime appends to) and
 * writes `docs/dogfood/<yyyy-ww>.md`: the same bytes `maina digest
 * --dogfood` writes, and what the release gate's dogfood-weeks evidence
 * reads.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DOGFOOD_REPORT } from "../../../packages/cli/src/commands/digest";
import { openDecisionDb } from "../../../packages/cli/src/decision-store";
import { appendDecision } from "../../../packages/core/src/decide/log/append";
import { hashValue } from "../../../packages/core/src/decide/log/hash";
import {
	type DigestEvent,
	gateLogEvents,
	parseGateLog,
	weekBounds,
} from "../../../packages/core/src/digest/build";
import { recordGateSubject } from "../../../packages/core/src/gate/overrides";
import {
	dogfoodWeeksEvidence,
	parseDogfoodReport,
} from "../../release/evidence/dogfood-weeks";
import { decisionLog, isoWeek, report } from "../report";

const SOURCE = DOGFOOD_REPORT.source;

const TS = Date.parse("2026-09-23T10:00:00.000Z"); // ISO week 2026-39

const EVENTS: readonly DigestEvent[] = [
	{
		ts: TS,
		tool: "shell",
		verdict: "ask",
		rule: "git.push.protected",
		override: false,
		crash: false,
	},
	{
		ts: TS + 1,
		tool: "shell",
		verdict: "deny",
		rule: "fs.delete.recursive",
		override: true,
		crash: false,
	},
];

describe("isoWeek", () => {
	test("computes ISO-8601 week keys", () => {
		expect(isoWeek("2026-09-25T10:00:00.000Z")).toBe("2026-39");
		expect(isoWeek("2026-01-01T00:00:00.000Z")).toBe("2026-01");
		expect(isoWeek("2025-12-29T00:00:00.000Z")).toBe("2026-01");
		expect(isoWeek("2027-01-01T00:00:00.000Z")).toBe("2026-53");
	});
});

describe("report", () => {
	test("writes docs/dogfood/<yyyy-ww>.md from the week's decision log events", () => {
		const bounds: Array<{ since: number; until: number }> = [];
		const writes: Array<{ path: string; content: string }> = [];
		const r = report("2026-39", {
			root: "/repo",
			readEvents: (b) => {
				bounds.push(b);
				return { ok: true, value: EVENTS };
			},
			writeFile: (path, content) => {
				writes.push({ path, content });
			},
		});
		expect(r).toEqual({ ok: true, value: "/repo/docs/dogfood/2026-39.md" });
		expect(bounds).toEqual([weekBounds("2026-39")]);
		expect(writes).toHaveLength(1);
		const md = writes[0]?.content ?? "";
		expect(md).toStartWith(`# Dogfood report 2026-39\n\n${SOURCE}\n`);
		expect(md).toContain("| **total** | 2 |");
		expect(md).toContain("| fs.delete.recursive | 1 |");
	});

	test("the report says it comes from the decision log", () => {
		expect(SOURCE).toContain("`.maina/decisions.db`");
		expect(SOURCE).not.toContain("log.jsonl");
	});

	test("rejects a malformed week key", () => {
		const r = report("2026-W39x", {
			root: "/repo",
			readEvents: () => ({ ok: true, value: [] }),
			writeFile: () => {},
		});
		expect(r.ok).toBe(false);
	});

	test("a decision log that cannot be read is a failure and writes nothing", () => {
		const writes: string[] = [];
		const r = report("2026-39", {
			root: "/repo",
			readEvents: () => ({ ok: false, error: "corrupt" }),
			writeFile: (path) => {
				writes.push(path);
			},
		});
		expect(r).toEqual({
			ok: false,
			error: "cannot read the decision log: corrupt",
		});
		expect(writes).toEqual([]);
	});

	// Golden (#350): the metrics and table layout are pinned byte for byte by
	// the pre-move fixtures; only the source line changed when the report
	// moved from the hook's log.jsonl to the decision log (#570).
	test.each([
		"2026-39",
		"2026-40",
	])("week %s matches the golden report apart from its source line", (week) => {
		const fixtures = join(
			import.meta.dir,
			"../../../packages/core/src/digest/__tests__/fixtures",
		);
		const { records } = parseGateLog(
			readFileSync(join(fixtures, "gate-log.jsonl"), "utf-8"),
		);
		const writes: string[] = [];
		const r = report(week, {
			root: "/repo",
			readEvents: () => ({ ok: true, value: gateLogEvents(records) }),
			writeFile: (_path, content) => {
				writes.push(content);
			},
		});
		expect(r.ok).toBe(true);
		const golden = readFileSync(
			join(fixtures, `dogfood-report-${week}.md`),
			"utf-8",
		).replace(
			"Generated by `bun run dogfood:report` from the dogfood PreToolUse hook log (`.maina/dogfood/log.jsonl`).",
			SOURCE,
		);
		expect(writes).toEqual([golden]);
	});
});

// #570: the gate decisions the dogfood hook's runtime logs reach the
// committed report, and the release gate counts that week as on v1.
describe("decision log to release gate", () => {
	let repo: string;

	beforeEach(() => {
		repo = mkdtempSync(join(tmpdir(), "maina-570-"));
	});

	afterEach(() => {
		rmSync(repo, { recursive: true, force: true });
	});

	test("a week of logged gate decisions is a week on the v1 runtime", () => {
		const mainaDir = join(repo, ".maina");
		const opened = openDecisionDb(mainaDir);
		if (!opened.ok) throw new Error(opened.error);
		const { db, close } = opened.value;
		// What the runtime gate appends for a rule-reached ask.
		const appended = appendDecision(
			{ db },
			{
				id: "d570",
				ts: TS,
				type: "action.risk",
				inputHash: hashValue("input"),
				schemaHash: hashValue("schema"),
				optionOrder: ["allow", "ask", "deny"],
				policyHash: hashValue("policy"),
				modelHash: hashValue("rules"),
				distribution: [
					{ answer: "allow", p: 0 },
					{ answer: "ask", p: 1 },
					{ answer: "deny", p: 0 },
				],
				answer: "ask",
				finalAction: "ask",
				latencyMs: 1,
			},
		);
		expect(appended.ok).toBe(true);
		expect(
			recordGateSubject(db, {
				decisionId: "d570",
				kind: "shell",
				targets: ["sudo rm -rf /opt/x"],
				classes: ["privilege.escalate"],
				rule: "ask",
				irreversible: true,
			}).ok,
		).toBe(true);
		close();

		const written = new Map<string, string>();
		const r = report("2026-39", {
			root: repo,
			readEvents: decisionLog(repo),
			writeFile: (path, content) => {
				written.set(path, content);
			},
		});
		expect(r.ok).toBe(true);
		const md = written.get(join(repo, "docs/dogfood/2026-39.md")) ?? "";
		// Labels only: the gated command never reaches the committed report.
		expect(md).not.toContain("sudo rm");
		expect(parseDogfoodReport(md)).toEqual({
			ok: true,
			value: { week: "2026-39", decisions: 1 },
		});
		const evidence = dogfoodWeeksEvidence(
			[{ path: "docs/dogfood/2026-39.md", text: md }],
			[],
			"https://github.com/mainahq/maina/actions/runs/1",
			new Date("2026-09-28T12:00:00Z"),
		);
		expect(evidence.ok && evidence.value.weeks[0]?.onV1Runtime).toBe(true);
	});
});
