/**
 * Tests for the weekly dogfood report (#286, FR-DOG-4; #570).
 *
 * The report reads one ISO week of gate decisions from the decision log
 * (`.maina/decisions.db`, which the dogfood hook's runtime appends to) and
 * writes `docs/dogfood/<yyyy-ww>.md`: the same bytes `maina digest
 * --dogfood` writes, and what the release gate's dogfood-weeks evidence
 * reads.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DOGFOOD_REPORT } from "../../../packages/cli/src/commands/digest";
import { openDecisionDb } from "../../../packages/cli/src/decision-store";
import { appendDecision } from "../../../packages/core/src/decide/log/append";
import { hashValue } from "../../../packages/core/src/decide/log/hash";
import {
	type DigestEvent,
	gateLogEvents,
	parseGateLog,
	weekBounds,
} from "../../../packages/core/src/digest/build";
import { recordGateSubject } from "../../../packages/core/src/gate/overrides";
import {
	dogfoodWeeksEvidence,
	parseDogfoodReport,
} from "../../release/evidence/dogfood-weeks";
import {
	askOutcomes,
	decisionLog,
	isoWeek,
	outcomesLine,
	report,
} from "../report";

const SOURCE = DOGFOOD_REPORT.source;

const TS = Date.parse("2026-09-23T10:00:00.000Z"); // ISO week 2026-39

const EVENTS: readonly DigestEvent[] = [
	{
		ts: TS,
		tool: "shell",
		verdict: "ask",
		rule: "git.push.protected",
		override: false,
		crash: false,
	},
	{
		ts: TS + 1,
		tool: "shell",
		verdict: "deny",
		rule: "fs.delete.recursive",
		override: true,
		crash: false,
	},
];

describe("isoWeek", () => {
	test("computes ISO-8601 week keys", () => {
		expect(isoWeek("2026-09-25T10:00:00.000Z")).toBe("2026-39");
		expect(isoWeek("2026-01-01T00:00:00.000Z")).toBe("2026-01");
		expect(isoWeek("2025-12-29T00:00:00.000Z")).toBe("2026-01");
		expect(isoWeek("2027-01-01T00:00:00.000Z")).toBe("2026-53");
	});
});

describe("report", () => {
	test("writes docs/dogfood/<yyyy-ww>.md from the week's decision log events", () => {
		const bounds: Array<{ since: number; until: number }> = [];
		const writes: Array<{ path: string; content: string }> = [];
		const r = report("2026-39", {
			root: "/repo",
			readEvents: (b) => {
				bounds.push(b);
				return { ok: true, value: EVENTS };
			},
			writeFile: (path, content) => {
				writes.push({ path, content });
			},
		});
		expect(r).toEqual({ ok: true, value: "/repo/docs/dogfood/2026-39.md" });
		expect(bounds).toEqual([weekBounds("2026-39")]);
		expect(writes).toHaveLength(1);
		const md = writes[0]?.content ?? "";
		expect(md).toStartWith(`# Dogfood report 2026-39\n\n${SOURCE}\n`);
		expect(md).toContain("| **total** | 2 |");
		expect(md).toContain("| fs.delete.recursive | 1 |");
	});

	test("the report says it comes from the decision log", () => {
		expect(SOURCE).toContain("`.maina/decisions.db`");
		expect(SOURCE).not.toContain("log.jsonl");
	});

	test("rejects a malformed week key", () => {
		const r = report("2026-W39x", {
			root: "/repo",
			readEvents: () => ({ ok: true, value: [] }),
			writeFile: () => {},
		});
		expect(r.ok).toBe(false);
	});

	test("a decision log that cannot be read is a failure and writes nothing", () => {
		const writes: string[] = [];
		const r = report("2026-39", {
			root: "/repo",
			readEvents: () => ({ ok: false, error: "corrupt" }),
			writeFile: (path) => {
				writes.push(path);
			},
		});
		expect(r).toEqual({
			ok: false,
			error: "cannot read the decision log: corrupt",
		});
		expect(writes).toEqual([]);
	});

	// Golden (#350): the metrics and table layout are pinned byte for byte by
	// the pre-move fixtures; only the source line changed when the report
	// moved from the hook's log.jsonl to the decision log (#570).
	test.each([
		"2026-39",
		"2026-40",
	])("week %s matches the golden report apart from its source line", (week) => {
		const fixtures = join(
			import.meta.dir,
			"../../../packages/core/src/digest/__tests__/fixtures",
		);
		const { records } = parseGateLog(
			readFileSync(join(fixtures, "gate-log.jsonl"), "utf-8"),
		);
		const writes: string[] = [];
		const r = report(week, {
			root: "/repo",
			readEvents: () => ({ ok: true, value: gateLogEvents(records) }),
			writeFile: (_path, content) => {
				writes.push(content);
			},
		});
		expect(r.ok).toBe(true);
		const golden = readFileSync(
			join(fixtures, `dogfood-report-${week}.md`),
			"utf-8",
		).replace(
			"Generated by `bun run dogfood:report` from the dogfood PreToolUse hook log (`.maina/dogfood/log.jsonl`).",
			SOURCE,
		);
		expect(writes).toEqual([golden]);
	});

	// The post hook appends `ran` records to the same log.jsonl: they are not
	// gate decisions, so the counts and the report stay as they were.
	test("ran records in the hook log leave the golden report unchanged", () => {
		const fixtures = join(
			import.meta.dir,
			"../../../packages/core/src/digest/__tests__/fixtures",
		);
		const text = readFileSync(join(fixtures, "gate-log.jsonl"), "utf-8");
		const ran = JSON.stringify({
			ts: "2026-09-23T10:00:00.000Z",
			kind: "ran",
			tool: "Bash",
			action: "ls",
			toolUseId: "t1",
			sessionId: "s1",
			root: "/repo",
			host: "claude-code",
		});
		const mixed = text
			.split("\n")
			.flatMap((l) => [l, ran])
			.join("\n");
		const render = (log: string): string[] => {
			const writes: string[] = [];
			report("2026-39", {
				root: "/repo",
				readEvents: () => ({
					ok: true,
					value: gateLogEvents(parseGateLog(log).records),
				}),
				writeFile: (_path, content) => {
					writes.push(content);
				},
			});
			return writes;
		};
		expect(render(mixed)).toEqual(render(text));
		expect(parseGateLog(mixed).malformed).toBe(parseGateLog(text).malformed);
	});
});

// FR-S1-4, FR-DOG-3: an ask's outcome, from the hook log. A `ran` record
// with the ask's tool use id (in the same session) means the user approved
// it; none means they refused or abandoned it.
describe("ask outcomes", () => {
	const WEEK = "2026-39";
	const line = (o: Record<string, unknown>): string => JSON.stringify(o);
	const ask = (
		id: string | undefined,
		session = "s1",
		ts = "2026-09-23T10:00:00.000Z",
	) =>
		line({
			ts,
			tool: "Bash",
			action: "rm -rf dist",
			verdict: "ask",
			reason: "irreversible",
			...(id === undefined ? {} : { toolUseId: id, sessionId: session }),
		});
	const ran = (id: string, session = "s1", ts = "2026-09-23T10:00:05.000Z") =>
		line({
			ts,
			kind: "ran",
			tool: "Bash",
			action: "rm -rf dist",
			toolUseId: id,
			sessionId: session,
			root: "/repo",
			host: "claude-code",
		});
	const allow = (id: string) =>
		line({
			ts: "2026-09-23T10:00:00.000Z",
			tool: "Bash",
			action: "ls",
			verdict: "allow",
			reason: "ok",
			toolUseId: id,
			sessionId: "s1",
		});

	test("pairs asks with ran records by tool use id within a session", () => {
		const log = [
			ask("a1"),
			ran("a1"),
			ask("a2"),
			ask("a3"),
			// Same tool use id, another session: not this ask's outcome.
			ran("a3", "s2"),
			// Asks without ids cannot be paired and are left out.
			ask(undefined),
			// Allows are not asks, whether or not they ran.
			allow("l1"),
			ran("l1"),
			"{not json",
		].join("\n");
		expect(askOutcomes(log, WEEK)).toEqual({
			asked: 3,
			ran: 1,
			denied: 0,
			notRan: 2,
		});
		expect(outcomesLine(log, WEEK)).toBe(
			"outcomes: of 3 asks with a tool use id, 1 ran (approved), 0 denied (auto-mode classifier), 2 did not (refused or abandoned)",
		);
	});

	test("only asks in the week count; their ran record may come later", () => {
		const log = [
			ask("a1", "s1", "2026-09-27T23:59:59.000Z"),
			ran("a1", "s1", "2026-09-28T00:00:10.000Z"),
			ask("a2", "s1", "2026-09-28T09:00:00.000Z"),
		].join("\n");
		expect(askOutcomes(log, WEEK)).toEqual({
			asked: 1,
			ran: 1,
			denied: 0,
			notRan: 0,
		});
	});

	// #659: a tool that fails after the user approved it still ran; the post
	// hook logs it from PostToolUseFailure as a `ran` record marked failed.
	test("an approved ask whose tool then failed counts as ran, not refused", () => {
		const failed = line({
			ts: "2026-09-23T10:00:05.000Z",
			kind: "ran",
			failed: true,
			tool: "Bash",
			action: "rm -rf dist",
			toolUseId: "a1",
			sessionId: "s1",
			root: "/repo",
			host: "claude-code",
		});
		const log = [ask("a1"), failed, ask("a2")].join("\n");
		expect(askOutcomes(log, WEEK)).toEqual({
			asked: 2,
			ran: 1,
			denied: 0,
			notRan: 1,
		});
	});

	// PermissionDenied: the auto-mode classifier denied the call. It did not
	// run, but the user did not refuse it either, so it is counted apart.
	test("an ask the classifier denied counts as denied, not refused", () => {
		const deny = (id: string, session = "s1") =>
			line({
				ts: "2026-09-23T10:00:05.000Z",
				kind: "denied",
				tool: "Bash",
				toolUseId: id,
				sessionId: session,
				root: "/repo",
				host: "claude-code",
			});
		const log = [
			ask("a1"),
			deny("a1"),
			ask("a2"),
			// Another session's denial is not this ask's outcome.
			deny("a2", "s2"),
			ask("a3"),
			ran("a3"),
		].join("\n");
		expect(askOutcomes(log, WEEK)).toEqual({
			asked: 3,
			ran: 1,
			denied: 1,
			notRan: 1,
		});
		expect(outcomesLine(log, WEEK)).toBe(
			"outcomes: of 3 asks with a tool use id, 1 ran (approved), 1 denied (auto-mode classifier), 1 did not (refused or abandoned)",
		);
	});

	test("an old log, with no ids, adds no outcomes line", () => {
		const fixtures = join(
			import.meta.dir,
			"../../../packages/core/src/digest/__tests__/fixtures",
		);
		const text = readFileSync(join(fixtures, "gate-log.jsonl"), "utf-8");
		expect(askOutcomes(text, WEEK)).toEqual({
			asked: 0,
			ran: 0,
			denied: 0,
			notRan: 0,
		});
		expect(outcomesLine(text, WEEK)).toBeUndefined();
		expect(outcomesLine("", WEEK)).toBeUndefined();
	});
});

// #570: the gate decisions the dogfood hook's runtime logs reach the
// committed report, and the release gate counts that week as on v1.
describe("decision log to release gate", () => {
	let repo: string;

	beforeEach(() => {
		repo = mkdtempSync(join(tmpdir(), "maina-570-"));
	});

	afterEach(() => {
		rmSync(repo, { recursive: true, force: true });
	});

	test("a week of logged gate decisions is a week on the v1 runtime", () => {
		const mainaDir = join(repo, ".maina");
		const opened = openDecisionDb(mainaDir);
		if (!opened.ok) throw new Error(opened.error);
		const { db, close } = opened.value;
		// What the runtime gate appends for a rule-reached ask.
		const appended = appendDecision(
			{ db },
			{
				id: "d570",
				ts: TS,
				type: "action.risk",
				inputHash: hashValue("input"),
				schemaHash: hashValue("schema"),
				optionOrder: ["allow", "ask", "deny"],
				policyHash: hashValue("policy"),
				modelHash: hashValue("rules"),
				distribution: [
					{ answer: "allow", p: 0 },
					{ answer: "ask", p: 1 },
					{ answer: "deny", p: 0 },
				],
				answer: "ask",
				finalAction: "ask",
				latencyMs: 1,
			},
		);
		expect(appended.ok).toBe(true);
		expect(
			recordGateSubject(db, {
				decisionId: "d570",
				kind: "shell",
				targets: ["sudo rm -rf /opt/x"],
				classes: ["privilege.escalate"],
				rule: "ask",
				irreversible: true,
			}).ok,
		).toBe(true);
		close();

		const written = new Map<string, string>();
		const r = report("2026-39", {
			root: repo,
			readEvents: decisionLog(repo),
			writeFile: (path, content) => {
				written.set(path, content);
			},
		});
		expect(r.ok).toBe(true);
		const md = written.get(join(repo, "docs/dogfood/2026-39.md")) ?? "";
		// Labels only: the gated command never reaches the committed report.
		expect(md).not.toContain("sudo rm");
		expect(parseDogfoodReport(md)).toEqual({
			ok: true,
			value: { week: "2026-39", decisions: 1 },
		});
		const evidence = dogfoodWeeksEvidence(
			[{ path: "docs/dogfood/2026-39.md", text: md }],
			[],
			"https://github.com/mainahq/maina/actions/runs/1",
			new Date("2026-09-28T12:00:00Z"),
		);
		expect(evidence.ok && evidence.value.weeks[0]?.onV1Runtime).toBe(true);
	});
});
