// Generated by scripts/version-source.ts from packages/core/package.json.
// Do not edit: `bun run version` regenerates it after `changeset version`.

/** The maina version. The only place the runtime reads it from. */
export const VERSION = "1.8.1";
