#!/usr/bin/env bun
/**
 * Weekly dogfood report (#286, FR-DOG-4).
 *
 * Reads the dogfood hook's `.maina/dogfood/log.jsonl`, keeps one ISO week
 * and writes `docs/dogfood/<yyyy-ww>.md` with the gate metrics: decision
 * counts, deny/ask rates, overrides, crashes (fail-closed asks), per-tool
 * volume and the top deny rules.
 *
 * Usage:
 *   bun run dogfood:report                 # current ISO week
 *   bun run dogfood:report --week 2026-39  # a specific week
 */

import type { LogRecord, Verdict } from "./hook";
import type { Result } from "./receipt-check";

export interface WeeklyMetrics {
	readonly week: string;
	readonly total: number;
	readonly verdicts: Readonly<Record<Verdict, number>>;
	readonly denyRate: number;
	readonly askRate: number;
	readonly overrides: number;
	/** overrides / (denies + overrides): how often a deny was contested. */
	readonly overrideRate: number;
	/** Hook crashes that failed closed to `ask`. */
	readonly crashes: number;
	readonly byTool: Readonly<Record<string, number>>;
	readonly topDenyRules: ReadonlyArray<{
		readonly rule: string;
		readonly count: number;
	}>;
}

export interface ReportDeps {
	readonly root: string;
	/** Returns the log text, or undefined when there is no log yet. */
	readonly readLog: () => string | undefined;
	readonly writeFile: (path: string, content: string) => void;
}

const WEEK_RE = /^\d{4}-\d{2}$/;
const VERDICTS: ReadonlySet<string> = new Set(["allow", "ask", "deny"]);

/** ISO-8601 week key `yyyy-ww` (UTC) for a timestamp. */
export function isoWeek(ts: string): string {
	const d = new Date(ts);
	const date = new Date(
		Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()),
	);
	// Thursday of this week decides the ISO year.
	const day = date.getUTCDay() || 7;
	date.setUTCDate(date.getUTCDate() + 4 - day);
	const year = date.getUTCFullYear();
	const jan1 = Date.UTC(year, 0, 1);
	const week = Math.ceil(((date.getTime() - jan1) / 86_400_000 + 1) / 7);
	return `${year}-${String(week).padStart(2, "0")}`;
}

function asRecord(v: unknown): LogRecord | undefined {
	if (typeof v !== "object" || v === null) return undefined;
	const r = v as Record<string, unknown>;
	if (
		typeof r.ts !== "string" ||
		Number.isNaN(Date.parse(r.ts)) ||
		typeof r.tool !== "string" ||
		typeof r.action !== "string" ||
		typeof r.verdict !== "string" ||
		!VERDICTS.has(r.verdict) ||
		typeof r.reason !== "string"
	) {
		return undefined;
	}
	return r as unknown as LogRecord;
}

export function parseLog(text: string): {
	readonly records: readonly LogRecord[];
	readonly malformed: number;
} {
	const records: LogRecord[] = [];
	let malformed = 0;
	for (const line of text.split("\n")) {
		if (line.trim() === "") continue;
		try {
			const rec = asRecord(JSON.parse(line));
			if (rec) records.push(rec);
			else malformed++;
		} catch {
			malformed++;
		}
	}
	return { records, malformed };
}

const ratio = (n: number, d: number): number => (d === 0 ? 0 : n / d);

/** Rule id is the reason prefix before the first colon (e.g. `protected-push`). */
function ruleOf(reason: string): string {
	return reason.replace(/^\[override\]\s*/, "").split(":")[0] ?? reason;
}

export function computeMetrics(
	records: readonly LogRecord[],
	week: string,
): WeeklyMetrics {
	const inWeek = records.filter((r) => isoWeek(r.ts) === week);
	const verdicts: Record<Verdict, number> = { allow: 0, ask: 0, deny: 0 };
	const byTool: Record<string, number> = {};
	const denyRules = new Map<string, number>();
	let overrides = 0;
	let crashes = 0;
	for (const r of inWeek) {
		verdicts[r.verdict]++;
		byTool[r.tool] = (byTool[r.tool] ?? 0) + 1;
		if (r.override) overrides++;
		if (r.reason.startsWith("hook crash")) crashes++;
		if (r.verdict === "deny") {
			const rule = ruleOf(r.reason);
			denyRules.set(rule, (denyRules.get(rule) ?? 0) + 1);
		}
	}
	const topDenyRules = [...denyRules.entries()]
		.map(([rule, count]) => ({ rule, count }))
		.sort((a, b) => b.count - a.count || a.rule.localeCompare(b.rule))
		.slice(0, 10);
	return {
		week,
		total: inWeek.length,
		verdicts,
		denyRate: ratio(verdicts.deny, inWeek.length),
		askRate: ratio(verdicts.ask, inWeek.length),
		overrides,
		overrideRate: ratio(overrides, verdicts.deny + overrides),
		crashes,
		byTool,
		topDenyRules,
	};
}

const pct = (x: number): string => `${(x * 100).toFixed(1)}%`;

export function renderReport(m: WeeklyMetrics): string {
	const tools = Object.entries(m.byTool)
		.sort((a, b) => b[1] - a[1])
		.map(([tool, n]) => `| ${tool} | ${n} |`);
	const rules = m.topDenyRules.map((r) => `| ${r.rule} | ${r.count} |`);
	return [
		`# Dogfood report ${m.week}`,
		"",
		"Generated by `bun run dogfood:report` from the dogfood PreToolUse hook log (`.maina/dogfood/log.jsonl`).",
		"",
		"## Decisions",
		"",
		"| verdict | count |",
		"| --- | --- |",
		`| allow | ${m.verdicts.allow} |`,
		`| ask | ${m.verdicts.ask} |`,
		`| deny | ${m.verdicts.deny} |`,
		`| **total** | ${m.total} |`,
		"",
		"## Gate health",
		"",
		`- Deny rate: ${pct(m.denyRate)}`,
		`- Ask rate: ${pct(m.askRate)}`,
		`- Overrides: ${m.overrides} (${pct(m.overrideRate)} of denies contested)`,
		`- Crashes (failed closed to ask): ${m.crashes}`,
		"",
		"## By tool",
		"",
		"| tool | count |",
		"| --- | --- |",
		...(tools.length > 0 ? tools : ["| (none) | 0 |"]),
		"",
		"## Top deny rules",
		"",
		"| rule | count |",
		"| --- | --- |",
		...(rules.length > 0 ? rules : ["| (none) | 0 |"]),
		"",
	].join("\n");
}

export function report(week: string, deps: ReportDeps): Result<string, string> {
	if (!WEEK_RE.test(week)) {
		return { ok: false, error: `Invalid week "${week}"; expected yyyy-ww.` };
	}
	const { records } = parseLog(deps.readLog() ?? "");
	const path = `${deps.root}/docs/dogfood/${week}.md`;
	deps.writeFile(path, renderReport(computeMetrics(records, week)));
	return { ok: true, value: path };
}

// ── CLI (imperative shell) ────────────────────────────────────────────────

if (import.meta.main) {
	const { existsSync, mkdirSync, readFileSync, writeFileSync } = await import(
		"node:fs"
	);
	const { dirname, resolve } = await import("node:path");
	const root = resolve(import.meta.dir, "../..");
	const argv = process.argv.slice(2);
	const i = argv.indexOf("--week");
	const week =
		(i >= 0 ? argv[i + 1] : undefined) ?? isoWeek(new Date().toISOString());
	const logPath = resolve(root, ".maina/dogfood/log.jsonl");
	const r = report(week, {
		root,
		readLog: () =>
			existsSync(logPath) ? readFileSync(logPath, "utf-8") : undefined,
		writeFile: (path, content) => {
			mkdirSync(dirname(path), { recursive: true });
			writeFileSync(path, content, "utf-8");
		},
	});
	if (r.ok) {
		process.stdout.write(`Wrote ${r.value}\n`);
	} else {
		process.stderr.write(`dogfood report: ${r.error}\n`);
		process.exitCode = 1;
	}
}
