#!/usr/bin/env bun
/**
 * Weekly dogfood report (#286, FR-DOG-4).
 *
 * Reads the dogfood hook's `.maina/dogfood/log.jsonl`, keeps one ISO week
 * and writes `docs/dogfood/<yyyy-ww>.md` with the gate metrics: decision
 * counts, deny/ask rates, overrides, crashes (fail-closed asks), per-tool
 * volume and the top deny rules.
 *
 * The metrics and the markdown live in `packages/core/src/digest` (#350),
 * shared with `maina digest`; this script only reads the log and writes
 * the file. Its output is pinned by a golden test.
 *
 * Usage:
 *   bun run dogfood:report                 # current ISO week
 *   bun run dogfood:report --week 2026-39  # a specific week
 */

import {
	buildDigest,
	gateLogEvents,
	isoWeek,
	isWeekKey,
	parseGateLog,
	type WeeklyDigest,
} from "../../packages/core/src/digest/build";
import { renderDigest } from "../../packages/core/src/digest/render";
import type { LogRecord } from "./hook";
import type { Result } from "./receipt-check";

export { isoWeek };
export type WeeklyMetrics = WeeklyDigest;

export interface ReportDeps {
	readonly root: string;
	/** Returns the log text, or undefined when there is no log yet. */
	readonly readLog: () => string | undefined;
	readonly writeFile: (path: string, content: string) => void;
}

const TITLE = "Dogfood report";
const SOURCE =
	"Generated by `bun run dogfood:report` from the dogfood PreToolUse hook log (`.maina/dogfood/log.jsonl`).";

export const parseLog = parseGateLog;

export function computeMetrics(
	records: readonly LogRecord[],
	week: string,
): WeeklyMetrics {
	return buildDigest(gateLogEvents(records), week);
}

export function renderReport(m: WeeklyMetrics): string {
	return renderDigest(m, { title: TITLE, source: SOURCE });
}

export function report(week: string, deps: ReportDeps): Result<string, string> {
	if (!isWeekKey(week)) {
		return { ok: false, error: `Invalid week "${week}"; expected yyyy-ww.` };
	}
	const { records } = parseLog(deps.readLog() ?? "");
	const path = `${deps.root}/docs/dogfood/${week}.md`;
	deps.writeFile(path, renderReport(computeMetrics(records, week)));
	return { ok: true, value: path };
}

// ── CLI (imperative shell) ────────────────────────────────────────────────

if (import.meta.main) {
	const { existsSync, mkdirSync, readFileSync, writeFileSync } = await import(
		"node:fs"
	);
	const { dirname, resolve } = await import("node:path");
	const root = resolve(import.meta.dir, "../..");
	const argv = process.argv.slice(2);
	const i = argv.indexOf("--week");
	const week =
		(i >= 0 ? argv[i + 1] : undefined) ?? isoWeek(new Date().toISOString());
	const logPath = resolve(root, ".maina/dogfood/log.jsonl");
	const r = report(week, {
		root,
		readLog: () =>
			existsSync(logPath) ? readFileSync(logPath, "utf-8") : undefined,
		writeFile: (path, content) => {
			mkdirSync(dirname(path), { recursive: true });
			writeFileSync(path, content, "utf-8");
		},
	});
	if (r.ok) {
		process.stdout.write(`Wrote ${r.value}\n`);
	} else {
		process.stderr.write(`dogfood report: ${r.error}\n`);
		process.exitCode = 1;
	}
}
