/**
 * The shape of `landing-proofs.json` and `public/gate-corpus.json` (#360,
 * FR-DOC-7): every verdict, count and receipt the landing page shows.
 *
 * Both files are generated by `scripts/landing-proofs.ts` from this repo:
 * the real rules engine over the labelled command corpus, the real spec
 * analyzer over a real feature directory, and the newest committed receipt.
 * Nothing here is typed by hand. `bun run docs:check` fails when they are
 * stale.
 */

export type Verdict = "allow" | "ask" | "deny";

/** What the rules stage alone concluded, before any backend answered. */
type RuleKind = Verdict | "no_rule";

/** One gate evaluation under the default policy, as the page shows it. */
export type GateRow = Readonly<{
	/** A preset id from `landing.ts`, or a corpus fixture id. */
	id: string;
	/** The command or action, as shown. */
	label: string;
	/** The host shown as the agent that attempted it. */
	agent: string;
	verdict: Verdict;
	rule: RuleKind;
	/** The gate's own reason, as it prints it. */
	reason: string;
	/** Action classes the classifier found. */
	classes: readonly string[];
	/** The answering backend's probability for each verdict. */
	distribution: readonly Readonly<{ answer: Verdict; p: number }>[];
	/** The backend that answered `action.risk` (`rules` by default). */
	backend: string;
}>;

/** A row of the try-your-own lookup table (short keys: it is fetched). */
export type CorpusRow = Readonly<{
	/** The command. */
	c: string;
	v: Verdict;
	/** The gate's reason. */
	r: string;
	/** Action classes. */
	k: readonly string[];
}>;

type ReceiptCheck = Readonly<{
	name: string;
	status: string;
	findings: number;
}>;

export type LandingProofs = Readonly<{
	gate: Readonly<{
		/** The `action.risk` backend of the default policy. */
		backend: string;
		/** Its confidence threshold: a less sure answer asks. */
		threshold: number;
		presets: Readonly<Record<string, GateRow>>;
		ledger: readonly GateRow[];
	}>;
	corpus: Readonly<{
		destructive: Readonly<{ total: number; held: number }>;
		obfuscated: Readonly<{ total: number; held: number }>;
		selfOverride: Readonly<{ total: number; denied: number }>;
		benign: Readonly<{ total: number; flagged: number }>;
	}>;
	proofs: Readonly<{
		/** A dogfood case the rules deny. */
		blocked: Readonly<{
			command: string;
			verdict: Verdict;
			reason: string;
			classes: readonly string[];
			fixture: string;
			source: string;
			issue: number;
		}>;
		/** An error the spec analyzer finds in a feature directory. */
		spec: Readonly<{
			feature: string;
			category: string;
			severity: string;
			message: string;
			errors: number;
			warnings: number;
		}>;
		/** The newest committed verification receipt. */
		receipt: Readonly<{
			hash: string;
			hashShort: string;
			prTitle: string;
			status: string;
			statusLabel: string;
			timestamp: string;
			diffSummary: string;
			href: string;
			passed: number;
			total: number;
			checks: readonly ReceiptCheck[];
		}>;
	}>;
}>;
