/**
 * Codex rules emitter and the apply_patch doctor check (FR-GATE-7).
 *
 * `emitCodexRules` turns the policy's static shell allow/deny lists into
 * Codex `prefix_rule` entries: stable (same rules, same bytes, whatever the
 * order) and parseable. It never emits an allow Codex would apply more
 * widely than maina's rule.
 *
 * `codexApplyPatchCheck` reports the enforcement gap in openai/codex#27833:
 * Codex runs a PreToolUse hook for `apply_patch` but does not enforce its
 * deny, so a file edit maina denies is still written.
 */

import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import type { RulePolicy } from "@mainahq/core";
import {
	CODEX_APPLY_PATCH_ISSUE,
	codexApplyPatchCheck,
	codexHookFiles,
	emitCodexRules,
} from "../codex-rules";
import { checkHostHealth, type HostHealthPorts } from "../health";

type Rules = Readonly<{
	allow: readonly RulePolicy[];
	deny: readonly RulePolicy[];
}>;

const policy = (rules: Rules) => ({ rules });

type PrefixRule = Readonly<{
	pattern: readonly string[];
	decision: string;
	justification?: string;
}>;

/**
 * A strict reader for what the emitter writes: comment lines, blank lines
 * and `prefix_rule(...)` blocks with one `key = value` per line, each value
 * a JSON-compatible Starlark literal. Anything else fails the parse.
 */
function parseRules(text: string): readonly PrefixRule[] {
	const rules: PrefixRule[] = [];
	const lines = text.split("\n");
	expect(lines.at(-1)).toBe("");
	let current: Record<string, unknown> | null = null;
	for (const line of lines.slice(0, -1)) {
		if (current === null) {
			if (line === "" || line.startsWith("#")) continue;
			expect(line).toBe("prefix_rule(");
			current = {};
			continue;
		}
		if (line === ")") {
			rules.push(current as PrefixRule);
			current = null;
			continue;
		}
		const field = /^ {4}([a-z_]+) = (.+),$/.exec(line);
		if (field === null) throw new Error(`unparseable line: ${line}`);
		current[field[1] as string] = JSON.parse(field[2] as string);
	}
	expect(current).toBeNull();
	return rules;
}

const SAMPLE: Rules = {
	deny: [
		{ match: "git push --force", reason: "force pushes rewrite history" },
		{ match: "npm publish" },
		{ match: "curl *", kind: "shell" },
	],
	allow: [
		{ match: "bun test" },
		{ match: "git status", kind: "shell", reason: "read-only" },
	],
};

describe("emitCodexRules", () => {
	test("translates deny rules to forbidden and allow rules to allow", () => {
		expect(parseRules(emitCodexRules(policy(SAMPLE)))).toEqual([
			{
				pattern: ["curl"],
				decision: "forbidden",
				justification: 'denied by maina policy rule "curl *"',
			},
			{
				pattern: ["git", "push", "--force"],
				decision: "forbidden",
				justification: "force pushes rewrite history",
			},
			{
				pattern: ["npm", "publish"],
				decision: "forbidden",
				justification: 'denied by maina policy rule "npm publish"',
			},
			{
				pattern: ["bun", "test"],
				decision: "allow",
				justification: 'allowed by maina policy rule "bun test"',
			},
			{
				pattern: ["git", "status"],
				decision: "allow",
				justification: "read-only",
			},
		]);
	});

	test("is stable: the same rules in any order give the same bytes", () => {
		const text = emitCodexRules(policy(SAMPLE));
		const shuffled: Rules = {
			deny: [...SAMPLE.deny].reverse(),
			allow: [...SAMPLE.allow].reverse(),
		};
		expect(emitCodexRules(policy(shuffled))).toBe(text);
		const duplicated: Rules = {
			deny: [...SAMPLE.deny, ...SAMPLE.deny, { match: " npm  publish " }],
			allow: [...SAMPLE.allow, ...SAMPLE.allow],
		};
		expect(emitCodexRules(policy(duplicated))).toBe(text);
		expect(text.endsWith("\n")).toBe(true);
	});

	test("pins the exact output", () => {
		expect(
			emitCodexRules(
				policy({
					deny: [{ match: "rm -rf /", reason: 'never "rm" the root' }],
					allow: [],
				}),
			),
		).toBe(
			[
				"# Generated by maina from the static shell rules in its gate policy.",
				"# Do not edit: regenerate it instead. Only shell rules translate; file,",
				"# MCP and network rules, and every action class, stay with maina's",
				"# PreToolUse hook, which still gates each command.",
				"",
				"prefix_rule(",
				'    pattern = ["rm", "-rf", "/"],',
				'    decision = "forbidden",',
				'    justification = "never \\"rm\\" the root",',
				")",
				"",
			].join("\n"),
		);
	});

	test("never widens an allow: a wildcard allow is skipped, not emitted", () => {
		// `curl *` as a prefix rule would also allow a bare `curl`, which the
		// maina rule does not.
		const text = emitCodexRules(
			policy({ deny: [], allow: [{ match: "curl *" }, { match: "npm *x" }] }),
		);
		expect(parseRules(text)).toEqual([]);
		expect(text).toContain('# skipped allow rule "curl *"');
		expect(text).toContain('# skipped allow rule "npm *x"');
	});

	test("never widens an allow whose spacing maina itself would never match", () => {
		// maina matches a plain rule against single-spaced argv, so "bun  test"
		// matches nothing there; the prefix ["bun", "test"] would allow `bun test`.
		const text = emitCodexRules(
			policy({
				deny: [],
				allow: [{ match: "bun  test" }, { match: " ls -la" }],
			}),
		);
		expect(parseRules(text)).toEqual([]);
		expect(text).toContain('# skipped allow rule "bun test"');
		expect(text).toContain('# skipped allow rule "ls -la"');
	});

	test("a wildcard a prefix cannot express is skipped for deny too", () => {
		const text = emitCodexRules(
			policy({ deny: [{ match: "git * --force" }, { match: "*" }], allow: [] }),
		);
		expect(parseRules(text)).toEqual([]);
		expect(text).toContain('# skipped deny rule "git * --force"');
	});

	test("tokens a shell would re-read (quotes, $, globs) are skipped", () => {
		const text = emitCodexRules(
			policy({
				deny: [{ match: 'echo "$HOME"' }, { match: "cat ~/.ssh/id_rsa" }],
				allow: [],
			}),
		);
		expect(parseRules(text)).toEqual([]);
		expect(text).toContain("# skipped deny rule");
	});

	test("only shell rules translate; other kinds stay with the gate", () => {
		const text = emitCodexRules(
			policy({
				deny: [
					{ match: ".env", kind: "file.write" },
					{ match: "evil.example.com", kind: "network" },
				],
				allow: [{ match: "linear/create_issue", kind: "mcp" }],
			}),
		);
		expect(parseRules(text)).toEqual([]);
		expect(text).not.toContain("skipped");
	});

	test("a reason with quotes, backslashes or newlines stays one parseable line", () => {
		const text = emitCodexRules(
			policy({
				deny: [{ match: "make deploy", reason: 'no "deploys"\\\nfrom agents' }],
				allow: [],
			}),
		);
		expect(parseRules(text)).toEqual([
			{
				pattern: ["make", "deploy"],
				decision: "forbidden",
				justification: 'no "deploys"\\\nfrom agents',
			},
		]);
	});

	test("a policy with no shell rules is just the header", () => {
		const text = emitCodexRules(policy({ allow: [], deny: [] }));
		expect(parseRules(text)).toEqual([]);
		expect(text.startsWith("# Generated by maina")).toBe(true);
	});
});

// ── apply_patch enforcement gap ───────────────────────────────────────────

const MAINA_HOOK = {
	type: "command",
	command: "/home/u/.maina/bin/maina hook PreToolUse",
};

const hooksJson = (matcher: string | undefined, command = MAINA_HOOK) =>
	JSON.stringify({
		hooks: {
			PreToolUse: [
				{ ...(matcher === undefined ? {} : { matcher }), hooks: [command] },
			],
		},
	});

const file = (path: string, text: string | null) => ({ path, text });

describe("codexApplyPatchCheck", () => {
	const PATH = "/h/.codex/hooks.json";

	test("no maina PreToolUse hook for Codex: nothing to report", () => {
		expect(codexApplyPatchCheck([file(PATH, null)])).toBeNull();
		expect(
			codexApplyPatchCheck([
				file(
					PATH,
					hooksJson(undefined, { type: "command", command: "./audit.sh" }),
				),
			]),
		).toBeNull();
		expect(codexApplyPatchCheck([file(PATH, "{not json")])).toBeNull();
		// A script that merely lives under a maina checkout is not maina's hook.
		expect(
			codexApplyPatchCheck([
				file(
					PATH,
					hooksJson(undefined, {
						type: "command",
						command: "/src/maina/scripts/lint.sh",
					}),
				),
			]),
		).toBeNull();
	});

	test("a maina hook that sees apply_patch warns that Codex ignores its deny", () => {
		// Codex also matches apply_patch by its `Edit` and `Write` aliases.
		for (const matcher of [
			undefined,
			"",
			"*",
			"apply_patch|Edit|Write",
			"^Edit$",
			"Bash|Write",
		]) {
			const check = codexApplyPatchCheck([file(PATH, hooksJson(matcher))]);
			expect(check, String(matcher)).toEqual({
				id: "codex",
				status: "warn",
				message: `Codex runs maina's PreToolUse hook for apply_patch but does not enforce its deny (${CODEX_APPLY_PATCH_ISSUE}), so a file edit maina denies is still written (${PATH})`,
			});
		}
	});

	test("a maina hook whose matcher misses apply_patch warns that edits are not gated", () => {
		const check = codexApplyPatchCheck([file(PATH, hooksJson("^Bash$"))]);
		expect(check).toEqual({
			id: "codex",
			status: "warn",
			message: `maina's Codex PreToolUse hook matcher "^Bash$" does not match apply_patch, so Codex file edits are not gated (${PATH})`,
		});
	});

	test("looks in $CODEX_HOME and the project's .codex, hooks.json and config.toml", () => {
		expect(codexHookFiles({ home: "/h", cwd: "/p" }, null)).toEqual([
			join("/h", ".codex", "hooks.json"),
			join("/h", ".codex", "config.toml"),
			join("/p", ".codex", "hooks.json"),
			join("/p", ".codex", "config.toml"),
		]);
		expect(
			codexHookFiles({ home: "/h", cwd: "/p", codexHome: "/opt/codex" }, "/p"),
		).toEqual([
			join("/opt/codex", "hooks.json"),
			join("/opt/codex", "config.toml"),
			join("/p", ".codex", "hooks.json"),
			join("/p", ".codex", "config.toml"),
		]);
	});

	test("from a subdirectory it also looks in the repo root's .codex", () => {
		expect(codexHookFiles({ home: "/h", cwd: "/p/pkg" }, "/p")).toEqual([
			join("/h", ".codex", "hooks.json"),
			join("/h", ".codex", "config.toml"),
			join("/p", ".codex", "hooks.json"),
			join("/p", ".codex", "config.toml"),
			join("/p/pkg", ".codex", "hooks.json"),
			join("/p/pkg", ".codex", "config.toml"),
		]);
	});

	test("inline [hooks] in config.toml count too", () => {
		const path = "/h/.codex/config.toml";
		const toml = [
			"[[hooks.PreToolUse]]",
			'matcher = "Edit|Write"',
			"",
			"[[hooks.PreToolUse.hooks]]",
			'type = "command"',
			'command = "/home/u/.maina/bin/maina hook PreToolUse"',
			"",
		].join("\n");
		expect(codexApplyPatchCheck([file(path, toml)])?.message).toContain(
			CODEX_APPLY_PATCH_ISSUE,
		);
		expect(codexApplyPatchCheck([file(path, "not = [toml")])).toBeNull();
	});

	test("doctor reports the gap among its runtime checks", async () => {
		// Run from a subdirectory: Codex reads the repo root's .codex.
		const hooks = join("/p", ".codex", "hooks.json");
		const ports: HostHealthPorts = {
			readFile: (path) => (path === hooks ? hooksJson(undefined) : null),
			listDir: () => null,
			realpath: (path) => path,
			repoRoot: async () => "/p",
			loadPolicy: async () => ({ ok: true, value: {} }),
			launchCwd: "/tmp/neutral",
			probe: async () => ({ kind: "not-found", command: "", path: "" }),
		};
		const health = await checkHostHealth(
			{
				ctx: { home: "/h", cwd: "/p/pkg", platform: "linux" },
				version: "0.0.0",
				platform: "linux",
				inheritedEnv: {},
			},
			ports,
		);
		const codex = health.runtime.find((c) => c.id === "codex");
		expect(codex?.status).toBe("warn");
		expect(codex?.message).toContain(CODEX_APPLY_PATCH_ISSUE);
		// A warning, not a failure: doctor still passes.
		expect(health.ok).toBe(true);
	});
});
