/**
 * Codex rules and the apply_patch doctor check (FR-GATE-7). Pure.
 *
 * `emitCodexRules` translates the policy's static shell allow/deny lists
 * into Codex execpolicy `prefix_rule` entries (a `.rules` file under
 * `~/.codex/rules/` or `<repo>/.codex/rules/`), so Codex's own approval
 * agrees with maina's rules before a hook runs:
 *
 *   deny rule    `decision = "forbidden"`
 *   allow rule   `decision = "allow"`
 *
 * A maina rule without a `*` matches a command and its argument prefix,
 * which is exactly a prefix rule. A deny ending in ` *` becomes the prefix
 * before it, which is broader and so stricter. Anything else a prefix rule
 * cannot express, and every allow with a `*` (the prefix would allow more
 * than the rule), is skipped with a comment rather than widened. Words a
 * shell would re-read (quotes, `$`, `~`, globs) are skipped the same way.
 * Codex applies the strictest matching rule, and maina's PreToolUse hook
 * still gates every command, so action classes (irreversible asks) are not
 * loosened by an allow here.
 *
 * The output is stable: sorted, deduplicated, byte-identical for the same
 * rules in any order.
 *
 * `codexApplyPatchCheck` reports openai/codex#27833 in `maina doctor`:
 * Codex runs a PreToolUse hook for `apply_patch` but does not enforce its
 * deny, so a file edit maina denies is still written.
 */

import { join } from "node:path";
import type { Policy } from "@mainahq/core";
import type { HealthCheck } from "./health";
import type { PathContext } from "./targets";

/** The upstream issue for the apply_patch enforcement gap. */
export const CODEX_APPLY_PATCH_ISSUE = "openai/codex#27833";

type RuleList = "allow" | "deny";

type PrefixRule = Readonly<{
	decision: "forbidden" | "allow";
	pattern: readonly string[];
	justification: string;
}>;

type Skipped = Readonly<{ skipped: string }>;

const HEADER = [
	"# Generated by maina from the static shell rules in its gate policy.",
	"# Do not edit: regenerate it instead. Only shell rules translate; file,",
	"# MCP and network rules, and every action class, stay with maina's",
	"# PreToolUse hook, which still gates each command.",
].join("\n");

/** Words that mean the same to a shell and to Codex's argv matching. */
const SHELL_SAFE = /^[A-Za-z0-9_@%+=:,./-]+$/;

/** A Starlark (and JSON) string literal on one line. */
function quote(value: string): string {
	const escaped = value
		.replace(/[\\"]/g, "\\$&")
		.replace(/\n/g, "\\n")
		.replace(/\r/g, "\\r")
		.replace(/\t/g, "\\t")
		// biome-ignore lint/suspicious/noControlCharactersInRegex: strip what the escapes above do not cover
		.replace(/[\u0000-\u001f\u007f]/g, "");
	return `"${escaped}"`;
}

function translate(
	rule: Policy["rules"]["allow"][number],
	list: RuleList,
): PrefixRule | Skipped | null {
	if (rule.kind !== undefined && rule.kind !== "shell") return null;
	const words = rule.match.trim().split(/\s+/).filter(Boolean);
	const normal = words.join(" ");
	const skip = (why: string): Skipped => ({
		skipped: `# skipped ${list} rule ${quote(normal)}: ${why}`,
	});
	let pattern = words;
	if (normal.includes("*")) {
		const prefix = words.slice(0, -1);
		const trailing =
			words.at(-1) === "*" &&
			prefix.length > 0 &&
			prefix.every((w) => !w.includes("*"));
		if (!trailing) return skip("a prefix rule cannot express this wildcard");
		if (list === "allow") {
			return skip("as a prefix it would allow more than the rule does");
		}
		pattern = prefix;
	}
	if (pattern.length === 0) return null;
	if (!pattern.every((w) => SHELL_SAFE.test(w))) {
		return skip("a shell would re-read one of its words");
	}
	return {
		decision: list === "deny" ? "forbidden" : "allow",
		pattern,
		justification:
			rule.reason ??
			`${list === "deny" ? "denied" : "allowed"} by maina policy rule ${quote(normal)}`,
	};
}

const RANK: Readonly<Record<PrefixRule["decision"], number>> = {
	forbidden: 0,
	allow: 1,
};

const keyOf = (rule: PrefixRule): string =>
	`${rule.decision} ${rule.pattern.join(" ")}`;

/** Code-point order, so the output does not depend on the machine's locale. */
const byCodePoint = (a: string, b: string): number =>
	a < b ? -1 : a > b ? 1 : 0;

function compare(a: PrefixRule, b: PrefixRule): number {
	return (
		RANK[a.decision] - RANK[b.decision] ||
		byCodePoint(a.pattern.join(" "), b.pattern.join(" ")) ||
		byCodePoint(a.justification, b.justification)
	);
}

function render(rule: PrefixRule): string {
	return [
		"prefix_rule(",
		`    pattern = [${rule.pattern.map(quote).join(", ")}],`,
		`    decision = ${quote(rule.decision)},`,
		`    justification = ${quote(rule.justification)},`,
		")",
	].join("\n");
}

/** The Codex `.rules` file for the policy's static shell rules. */
export function emitCodexRules(
	policy: Readonly<{ rules: Policy["rules"] }>,
): string {
	const translated = [
		...policy.rules.deny.map((r) => translate(r, "deny")),
		...policy.rules.allow.map((r) => translate(r, "allow")),
	];
	const seen = new Set<string>();
	const rules = translated
		.filter((t): t is PrefixRule => t !== null && !("skipped" in t))
		.sort(compare)
		.filter((rule) => {
			const key = keyOf(rule);
			if (seen.has(key)) return false;
			seen.add(key);
			return true;
		});
	const skipped = [
		...new Set(
			translated.flatMap((t) =>
				t !== null && "skipped" in t ? [t.skipped] : [],
			),
		),
	].sort(byCodePoint);
	const sections = [
		HEADER,
		...rules.map(render),
		...(skipped.length > 0 ? [skipped.join("\n")] : []),
	];
	return `${sections.join("\n\n")}\n`;
}

// ── apply_patch enforcement gap ───────────────────────────────────────────

type HookFile = Readonly<{ path: string; text: string | null }>;

type MainaHook = Readonly<{ path: string; matcher: string | undefined }>;

const isObj = (v: unknown): v is Readonly<Record<string, unknown>> =>
	typeof v === "object" && v !== null && !Array.isArray(v);

/** The `hooks.json` files Codex reads: `$CODEX_HOME`'s and the project's. */
export function codexHookFiles(
	ctx: Pick<PathContext, "home" | "cwd" | "codexHome">,
): readonly string[] {
	return [
		join(ctx.codexHome ?? join(ctx.home, ".codex"), "hooks.json"),
		join(ctx.cwd, ".codex", "hooks.json"),
	];
}

function parse(text: string): unknown {
	try {
		return JSON.parse(text);
	} catch {
		return null;
	}
}

/** maina's hook command: its launcher or CLI running `hook <event>`. */
const MAINA_HOOK = /maina.*\shook(\s|$)/;

/** maina's PreToolUse hook groups in one `hooks.json`. */
function mainaHooks(file: HookFile): readonly MainaHook[] {
	if (file.text === null) return [];
	const config = parse(file.text);
	const hooks = isObj(config) && isObj(config.hooks) ? config.hooks : {};
	const groups = Array.isArray(hooks.PreToolUse) ? hooks.PreToolUse : [];
	return groups.flatMap((group): MainaHook[] => {
		if (!isObj(group) || !Array.isArray(group.hooks)) return [];
		const ours = group.hooks.some(
			(h) =>
				isObj(h) && typeof h.command === "string" && MAINA_HOOK.test(h.command),
		);
		const matcher =
			typeof group.matcher === "string" ? group.matcher : undefined;
		return ours ? [{ path: file.path, matcher }] : [];
	});
}

/** Whether a Codex matcher (a regex; empty or `*` for all) hits apply_patch. */
function coversApplyPatch(matcher: string | undefined): boolean {
	if (matcher === undefined || matcher === "" || matcher === "*") return true;
	try {
		return new RegExp(matcher).test("apply_patch");
	} catch {
		return false;
	}
}

/**
 * The apply_patch gap for the Codex `hooks.json` files given, or null when
 * none registers maina's PreToolUse hook. A warning, not a failure: nothing
 * maina can fix, but a deny it logs for an edit does not stop the edit.
 */
export function codexApplyPatchCheck(
	files: readonly HookFile[],
): HealthCheck<"codex"> | null {
	const hooks = files.flatMap(mainaHooks);
	const gated = hooks.find((h) => coversApplyPatch(h.matcher));
	if (gated !== undefined) {
		return {
			id: "codex",
			status: "warn",
			message: `Codex runs maina's PreToolUse hook for apply_patch but does not enforce its deny (${CODEX_APPLY_PATCH_ISSUE}), so a file edit maina denies is still written (${gated.path})`,
		};
	}
	const [missed] = hooks;
	if (missed === undefined) return null;
	return {
		id: "codex",
		status: "warn",
		message: `maina's Codex PreToolUse hook matcher ${JSON.stringify(missed.matcher)} does not match apply_patch, so Codex file edits are not gated (${missed.path})`,
	};
}
