/**
 * Index page generator for `.maina/receipts/index.html`.
 *
 * Walks the receipts directory, reads each `<hash>/receipt.json`, and renders
 * a static HTML index listing the most-recent receipts. Designed for
 * GitHub Pages: zero runtime JS, links resolve as relative paths.
 *
 * The directory layout this consumes:
 *
 *   .maina/receipts/
 *     index.html           <- generated by this module
 *     <hash>/
 *       receipt.json
 *       index.html         <- per-receipt page (rendered by ./render)
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Receipt } from "./types";

export interface IndexPageOptions {
	/** Max entries to render. Default 20 — keeps the page readable. */
	limit?: number;
	/** Custom HTML title. Defaults to "Maina receipts". */
	title?: string;
}

export interface IndexEntry {
	hash: string;
	prTitle: string;
	repo: string;
	timestamp: string;
	status: "passed" | "failed" | "partial";
	passedCount: number;
	totalCount: number;
}

export type IndexPageResult =
	| { ok: true; htmlPath: string; entries: number }
	| { ok: false; code: "io"; message: string };

/**
 * Read every receipt under `receiptsDir` and render `index.html` listing them
 * in newest-first order.
 */
export function writeIndexPage(
	receiptsDir: string,
	options: IndexPageOptions = {},
): IndexPageResult {
	try {
		const limit = clampLimit(options.limit);
		const entries = collectEntries(receiptsDir, limit);
		const html = renderIndexHtml(entries, options.title ?? "Maina receipts");
		const htmlPath = join(receiptsDir, "index.html");
		writeFileSync(htmlPath, html, "utf-8");
		return { ok: true, htmlPath, entries: entries.length };
	} catch (e) {
		const message = e instanceof Error ? e.message : String(e);
		return { ok: false, code: "io", message };
	}
}

/** Clamp the limit to a non-negative safe integer; `undefined` → default 20. */
function clampLimit(raw: number | undefined): number {
	if (raw === undefined) return 20;
	if (typeof raw !== "number" || !Number.isFinite(raw)) return 20;
	return Math.max(0, Math.trunc(raw));
}

/** Render the index HTML — exported for tests. */
export function renderIndexHtml(
	entries: ReadonlyArray<IndexEntry>,
	title: string,
): string {
	const rows = entries.map(renderRow).join("\n");
	const empty = entries.length === 0;

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="description" content="Maina proof-of-correctness receipts — newest first.">
<style>
:root { color-scheme: light dark; }
body { font: 15px/1.55 system-ui, -apple-system, sans-serif; max-width: 920px; margin: 2rem auto; padding: 0 1.25rem; }
h1 { font-size: 1.5rem; margin: 0 0 0.5rem 0; }
.meta { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.82rem; opacity: 0.7; margin-bottom: 1.5rem; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 0.5rem 0.6rem; border-bottom: 1px solid rgba(127,127,127,0.18); vertical-align: top; }
th { font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; opacity: 0.65; }
.status { display: inline-block; padding: 0.1rem 0.55rem; border-radius: 999px; font-weight: 600; font-size: 0.78rem; }
.status-passed { background: oklch(0.92 0.1 145); color: oklch(0.25 0.15 145); }
.status-failed { background: oklch(0.92 0.1 25); color: oklch(0.25 0.15 25); }
.status-partial { background: oklch(0.92 0.08 90); color: oklch(0.3 0.15 90); }
.title-cell a { color: inherit; text-decoration: none; font-weight: 500; }
.title-cell a:hover { text-decoration: underline; }
.hash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.78rem; opacity: 0.65; }
.timestamp { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.8rem; opacity: 0.75; }
.empty { padding: 2rem 1rem; text-align: center; opacity: 0.7; }
footer { margin-top: 2.5rem; padding-top: 1rem; border-top: 1px solid rgba(127,127,127,0.2); font-size: 0.82rem; opacity: 0.7; }
a { color: oklch(0.55 0.2 250); }
@media (prefers-color-scheme: dark) { a { color: oklch(0.75 0.15 250); } }
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
<p class="meta">Maina proof-of-correctness receipts — newest first.</p>

${
	empty
		? `<div class="empty">Maina hasn't recorded any receipts in this directory yet. Run <code>maina receipt</code> on a verified change to publish one.</div>`
		: `<table>
<thead>
<tr>
  <th>Status</th>
  <th>PR</th>
  <th>Checks</th>
  <th>Timestamp</th>
  <th>Hash</th>
</tr>
</thead>
<tbody>
${rows}
</tbody>
</table>`
}

<footer>
Receipt format: v1 (<a href="https://schemas.mainahq.com/v1.json">schemas.mainahq.com/v1.json</a>).
Verify any receipt offline with <code>maina verify-receipt &lt;path&gt;</code>.
</footer>
</body>
</html>`;
}

function renderRow(entry: IndexEntry): string {
	const safeStatus = receiptStatusClass(entry.status);
	const safeHash = HEX64.test(entry.hash) ? entry.hash : "";
	const statusLabel =
		entry.status === "passed"
			? `passed ${entry.passedCount} of ${entry.totalCount}`
			: entry.status === "partial"
				? `partial — ${entry.passedCount}/${entry.totalCount} held`
				: `failed — ${entry.passedCount}/${entry.totalCount} held`;

	const titleCell = safeHash
		? `<a href="./${safeHash}/index.html">${escapeHtml(entry.prTitle)}</a>`
		: escapeHtml(entry.prTitle);

	return `<tr>
  <td><span class="status status-${safeStatus}">${escapeHtml(entry.status)}</span></td>
  <td class="title-cell">${titleCell}<br><span class="hash">${escapeHtml(entry.repo)}</span></td>
  <td>${escapeHtml(statusLabel)}</td>
  <td class="timestamp">${escapeHtml(entry.timestamp)}</td>
  <td class="hash">${escapeHtml(entry.hash.slice(0, 12))}…</td>
</tr>`;
}

const HEX64 = /^[0-9a-f]{64}$/;

/** Defense-in-depth — receipts that bypass schema validation (tampered JSON
 * loaded directly from disk) shouldn't be able to inject HTML attributes via
 * an unexpected `status` value. */
function receiptStatusClass(s: string): "passed" | "failed" | "partial" {
	return s === "passed" || s === "failed" || s === "partial"
		? (s as "passed" | "failed" | "partial")
		: "failed";
}

function collectEntries(receiptsDir: string, limit: number): IndexEntry[] {
	if (!existsSync(receiptsDir)) return [];
	const dirNames = readdirSync(receiptsDir, { withFileTypes: true })
		.filter((e) => e.isDirectory() && /^[0-9a-f]{64}$/.test(e.name))
		.map((e) => e.name);

	const entries: IndexEntry[] = [];
	for (const dir of dirNames) {
		const receipt = readReceipt(join(receiptsDir, dir, "receipt.json"));
		if (!receipt) continue;
		entries.push({
			hash: receipt.hash,
			prTitle: receipt.prTitle,
			repo: receipt.repo,
			timestamp: receipt.timestamp,
			status: receipt.status,
			passedCount: receipt.checks.filter((c) => c.status === "passed").length,
			totalCount: receipt.checks.length,
		});
	}

	entries.sort((a, b) => b.timestamp.localeCompare(a.timestamp));
	return entries.slice(0, limit);
}

function readReceipt(path: string): Receipt | null {
	try {
		if (!existsSync(path)) return null;
		const text = readFileSync(path, "utf-8");
		return JSON.parse(text) as Receipt;
	} catch {
		return null;
	}
}

function escapeHtml(s: string): string {
	return s
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#39;");
}
