#!/usr/bin/env bun
/**
 * The docs generator and its check (#357, FR-DOC-3, FR-DOC-6).
 *
 * Every count, version and name the docs state comes from the code. This
 * script renders them from the registries: the CLI program (commands), the
 * MCP catalog (tools), the host adapters' hook maps (hook events), the zod
 * config and policy schemas, the decision catalog and the privacy config.
 * The roadmap and the changelog are rendered from the changesets.
 *
 *   bun scripts/docs-manifest.ts           write every generated file
 *   bun scripts/docs-manifest.ts --json    print the facts as JSON
 *   bun scripts/docs-manifest.ts --check   fail when a generated file is
 *                                          stale, or when a hand-written
 *                                          page states a count, a version,
 *                                          an MCP tool or a maina command
 *                                          not taken from facts.ts
 *
 * Hand-written MDX takes its facts from `packages/docs/src/data/facts.ts`
 * (`{facts.version}`, `{facts.commands.count}`). A line that must state a
 * literal (a historical note) carries `{/* docs-manifest: ignore *\/}` or
 * `<!-- docs-manifest: ignore -->` on it or on the line before.
 */

import {
	mkdirSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { createProgram } from "../packages/cli/src/program";
import { configJsonSchema } from "../packages/core/src/config/schema";
import { DECISION_CATALOG } from "../packages/core/src/decide/types-catalog";
import { DEFAULT_POLICY } from "../packages/core/src/policy/defaults";
import {
	DECISION_TYPES,
	isLockedClass,
	policyJsonSchema,
} from "../packages/core/src/policy/schema";
import { TELEMETRY_CHANNELS } from "../packages/core/src/telemetry/consent";
import { VERSION } from "../packages/core/src/version";
import {
	ALL_TOOLS,
	DEEPWIKI_TOOLS,
	DEFAULT_TOOLS,
	TOOL_USAGE,
} from "../packages/mcp/src/catalog";
import { PLUGIN } from "../packages/plugins/src/definition";
import { CLAUDE_HOOK_MAP } from "../packages/runtime/src/adapters/claude-code";
import { CODEX_HOOK_MAP } from "../packages/runtime/src/adapters/codex";
import { CURSOR_HOOK_MAP } from "../packages/runtime/src/adapters/cursor";
import {
	type HostHookMap,
	LIFECYCLE_EVENTS,
	type LifecycleEvent,
} from "../packages/runtime/src/adapters/hook-map";
import { GENERATED_DOCS } from "./docs-generated";

export { GENERATED_DOCS };

const ROOT = join(import.meta.dir, "..");
const DOCS = "packages/docs/src/content/docs";
const FACTS_FILE = "packages/docs/src/data/facts.ts";
const MARKER = "Generated by scripts/docs-manifest.ts";

// ── Registries ──────────────────────────────────────────────────────────────

/** A Commander command, typed from the CLI so this script needs no import of it. */
type Command = ReturnType<typeof createProgram>;

type CommanderInternals = Readonly<{ _hidden?: boolean }>;

const isHidden = (cmd: Command): boolean =>
	(cmd as unknown as CommanderInternals)._hidden === true;

let program: Command | undefined;

/**
 * The CLI's top-level commands, in registration order. Built once: creating
 * the program also registers its process exit hooks.
 */
function cliCommands(): readonly Command[] {
	program ??= createProgram();
	return program.commands;
}

const HOSTS: readonly Readonly<{ name: string; map: HostHookMap }>[] = [
	{ name: "Claude Code", map: CLAUDE_HOOK_MAP },
	{ name: "Codex", map: CODEX_HOOK_MAP },
	{ name: "Cursor", map: CURSOR_HOOK_MAP },
];

const LIFECYCLE = Object.keys(LIFECYCLE_EVENTS) as LifecycleEvent[];

function readJson(path: string): Readonly<Record<string, unknown>> {
	try {
		return JSON.parse(readFileSync(path, "utf-8")) as Record<string, unknown>;
	} catch {
		return {};
	}
}

function listDir(dir: string): string[] {
	try {
		return readdirSync(dir).sort();
	} catch {
		return [];
	}
}

const isFile = (path: string): boolean => {
	try {
		return statSync(path).isFile();
	} catch {
		return false;
	}
};

/** Versions of the published packages (those not marked private). */
function packageVersions(root: string): Readonly<Record<string, string>> {
	const out: Record<string, string> = {};
	for (const dir of listDir(join(root, "packages"))) {
		const pkg = readJson(join(root, "packages", dir, "package.json"));
		if (pkg.private === true) continue;
		if (typeof pkg.name === "string" && typeof pkg.version === "string") {
			out[pkg.name] = pkg.version;
		}
	}
	return out;
}

function skillNames(root: string): string[] {
	const dir = join(root, "packages", "skills");
	return listDir(dir).filter((name) => isFile(join(dir, name, "SKILL.md")));
}

// ── Facts ───────────────────────────────────────────────────────────────────

export type Facts = Readonly<{
	version: string;
	licence: string;
	packages: Readonly<Record<string, string>>;
	commands: Readonly<{
		count: number;
		names: readonly string[];
		internal: readonly string[];
	}>;
	mcpTools: Readonly<{
		default: readonly string[];
		deepwiki: readonly string[];
		all: readonly string[];
	}>;
	skills: Readonly<{ count: number; names: readonly string[] }>;
	decisionTypes: Readonly<{ count: number; names: readonly string[] }>;
	hookEvents: Readonly<{ count: number; names: readonly string[] }>;
	hosts: readonly string[];
	telemetry: Readonly<{
		channels: readonly string[];
		onByDefault: readonly string[];
		summary: string;
	}>;
}>;

/** "a", "a and b", "a, b and c". */
const prose = (items: readonly string[]): string =>
	items.length < 2
		? items.join("")
		: `${items.slice(0, -1).join(", ")} and ${items.at(-1)}`;

export function telemetrySummary(on: readonly string[]): string {
	const off = TELEMETRY_CHANNELS.filter((c) => !on.includes(c));
	if (off.length === 0) return `${prose(on)} are on by default.`;
	const optIn = `${prose(off)} ${off.length === 1 ? "is" : "are each"} opt-in, turned on in your user policy (~/.maina/policy.json)`;
	if (on.length === 0) return `Telemetry is off by default: ${optIn}.`;
	return `${prose(on)} ${on.length === 1 ? "is" : "are"} on by default; ${optIn}.`;
}

export function collectFacts(root: string): Facts {
	const commands = cliCommands();
	const visible = commands.filter((c) => !isHidden(c)).map((c) => c.name());
	const internal = commands.filter(isHidden).map((c) => c.name());
	const skills = skillNames(root);
	const cli = readJson(join(root, "packages", "cli", "package.json"));
	const onByDefault = TELEMETRY_CHANNELS.filter(
		(c) => DEFAULT_POLICY.telemetry[c],
	);
	return {
		version: VERSION,
		licence: typeof cli.license === "string" ? cli.license : "",
		packages: packageVersions(root),
		commands: { count: visible.length, names: visible, internal },
		mcpTools: {
			default: [...DEFAULT_TOOLS],
			deepwiki: [...DEEPWIKI_TOOLS],
			all: [...ALL_TOOLS],
		},
		skills: { count: skills.length, names: skills },
		decisionTypes: { count: DECISION_TYPES.length, names: [...DECISION_TYPES] },
		hookEvents: { count: LIFECYCLE.length, names: LIFECYCLE },
		hosts: HOSTS.map((h) => h.name),
		telemetry: {
			channels: [...TELEMETRY_CHANNELS],
			onByDefault,
			summary: telemetrySummary(onByDefault),
		},
	};
}

// ── facts.ts, formatted the way Biome formats it ────────────────────────────

const LINE_WIDTH = 80;
const TAB_WIDTH = 2;

type Json = string | number | boolean | readonly Json[] | JsonObject;
type JsonObject = Readonly<{ [key: string]: Json }>;

const tsKey = (key: string): string =>
	/^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);

function tsValue(value: Json, depth: number, lead: number): string {
	const pad = "\t".repeat(depth + 1);
	const close = "\t".repeat(depth);
	if (Array.isArray(value)) {
		const items = value.map((v) => tsValue(v, depth + 1, 0));
		const inline = `[${items.join(", ")}]`;
		if (items.length === 0 || lead + inline.length + 1 <= LINE_WIDTH) {
			return inline;
		}
		return `[\n${items.map((i) => `${pad}${i},`).join("\n")}\n${close}]`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value as JsonObject).map(([k, v]) => {
			const head = `${pad}${tsKey(k)}:`;
			const width = (depth + 1) * TAB_WIDTH + tsKey(k).length + 2;
			const rendered = tsValue(v, depth + 1, width);
			const long =
				typeof v === "string" && width + rendered.length + 1 > LINE_WIDTH;
			return long ? `${head}\n${pad}\t${rendered},` : `${head} ${rendered},`;
		});
		return `{\n${entries.join("\n")}\n${close}}`;
	}
	return JSON.stringify(value);
}

function renderFactsModule(facts: Facts): string {
	return [
		`// ${MARKER} from the code registries.`,
		"// Do not edit: run `bun run docs:generate`.",
		"",
		"/** Versions, counts and names the docs state, taken from the code. */",
		`export const facts = ${tsValue(facts as unknown as Json, 0, 0)} as const;`,
		"",
	].join("\n");
}

// ── MDX helpers ─────────────────────────────────────────────────────────────

const CODE_SPAN = /(`+)(?:[^`]|[^`][\s\S]*?[^`])\1(?!`)/g;

/** Escapes what MDX would read as JSX or an expression, outside code spans. */
function escapeText(text: string): string {
	const plain = (s: string): string =>
		s
			.replace(/[{}]/g, (c) => `\\${c}`)
			.replace(/</g, "&lt;")
			.replace(/(^[ \t]*>)|>/gm, (m, quote) => (quote ? m : "&gt;"));
	let out = "";
	let last = 0;
	for (const m of text.matchAll(CODE_SPAN)) {
		out += plain(text.slice(last, m.index)) + m[0];
		last = m.index + m[0].length;
	}
	return out + plain(text.slice(last));
}

/** Markdown made safe for MDX: fenced code untouched, the rest escaped. */
function escapeMarkdown(md: string): string {
	const out: string[] = [];
	let prose: string[] = [];
	let fence: string | null = null;
	const flush = (): void => {
		if (prose.length === 0) return;
		out.push(
			escapeText(prose.join("\n")).replace(
				/^(import|export)\b/gm,
				(w) => `&#${w.charCodeAt(0)};${w.slice(1)}`,
			),
		);
		prose = [];
	};
	for (const line of md.split("\n")) {
		const marker = /^\s*(`{3,}|~{3,})/.exec(line)?.[1];
		if (fence === null && marker) {
			flush();
			fence = marker;
			out.push(line);
		} else if (fence !== null) {
			out.push(line);
			if (marker?.startsWith(fence)) fence = null;
		} else {
			prose.push(line);
		}
	}
	flush();
	return out.join("\n");
}

/** One table cell: escaped, on one line, pipes escaped. */
const cell = (text: string): string =>
	escapeText(text.replace(/\s*\n\s*/g, " ")).replace(/\|/g, "\\|");

const code = (text: string): string => `\`${text.replace(/\|/g, "\\|")}\``;

function table(
	head: readonly string[],
	rows: readonly (readonly string[])[],
): string {
	return [
		`| ${head.join(" | ")} |`,
		`|${head.map(() => "---").join("|")}|`,
		...rows.map((r) => `| ${r.join(" | ")} |`),
	].join("\n");
}

function mdxPage(title: string, description: string, body: string): string {
	return [
		"---",
		`title: ${JSON.stringify(title)}`,
		`description: ${JSON.stringify(description)}`,
		"---",
		"",
		`{/* ${MARKER}. Do not edit: run \`bun run docs:generate\`. */}`,
		"",
		body.trimEnd(),
		"",
	].join("\n");
}

// ── Reference: commands ─────────────────────────────────────────────────────

type OptionView = Readonly<{
	flags: string;
	description: string;
	defaultValue?: unknown;
	hidden?: boolean;
}>;

function defaultText(value: unknown): string {
	if (typeof value === "string" && value !== "") return code(value);
	if (typeof value === "number") return code(String(value));
	return "";
}

function optionsTable(cmd: Command): string {
	const options = (cmd.options as readonly OptionView[]).filter(
		(o) => o.hidden !== true,
	);
	if (options.length === 0) return "";
	return table(
		["Option", "Description", "Default"],
		options.map((o) => [
			code(o.flags),
			cell(o.description),
			defaultText(o.defaultValue),
		]),
	);
}

function commandSection(cmd: Command, prefix: string, level: number): string {
	const name = `${prefix} ${cmd.name()}`.trim();
	const usage = cmd.usage().replace(/^\[options\]\s*/, "");
	const heading = `${"#".repeat(level)} \`${name}${usage === "" || usage === "[command]" ? "" : ` ${usage}`}\``;
	const parts = [heading, "", cell(cmd.description())];
	const aliases = cmd.aliases();
	if (aliases.length > 0) {
		parts.push("", `Aliases: ${aliases.map((a) => code(a)).join(", ")}.`);
	}
	const options = optionsTable(cmd);
	if (options !== "") parts.push("", options);
	const subs = cmd.commands.filter((c) => !isHidden(c));
	for (const sub of subs) {
		parts.push("", commandSection(sub, name, Math.min(level + 1, 4)));
	}
	return parts.join("\n");
}

function renderCommands(commands: readonly Command[]): string {
	const visible = commands.filter((c) => !isHidden(c));
	const internal = commands.filter(isHidden);
	const body = [
		"Every command `maina --help` lists, with its options, read from the CLI's command definitions. Run `maina <command> --help` for the same text in your terminal.",
		"",
		...visible.map((c) => `${commandSection(c, "maina", 2)}\n`),
		"## Internal commands",
		"",
		"Registered and callable by name, but left out of `maina --help`.",
		"",
		table(
			["Command", "Description"],
			internal.map((c) => [code(`maina ${c.name()}`), cell(c.description())]),
		),
	];
	return mdxPage(
		"Commands reference",
		"Every maina command and its options, generated from the CLI.",
		body.join("\n"),
	);
}

// ── Reference: MCP tools ────────────────────────────────────────────────────

function renderMcpTools(): string {
	const rows = (tools: readonly (typeof ALL_TOOLS)[number][]) =>
		table(
			["Tool", "When to use"],
			tools.map((t) => [code(t), cell(TOOL_USAGE[t])]),
		);
	const body = [
		"The tools the maina MCP server can register, read from its catalog.",
		"",
		"## Default tools",
		"",
		"Registered when no allow-list is given.",
		"",
		rows(DEFAULT_TOOLS),
		"",
		"## DeepWiki-compatible tools",
		"",
		"Registered only when allow-listed, with the `--tools` flag or the `MAINA_MCP_TOOLS` environment variable (comma-separated; `default` stands for the default set, so `default,ask_question` adds one).",
		"",
		rows(DEEPWIKI_TOOLS),
	];
	return mdxPage(
		"MCP tools reference",
		"Every MCP tool maina's server can register, generated from its catalog.",
		body.join("\n"),
	);
}

// ── Reference: hooks ────────────────────────────────────────────────────────

function renderHooks(): string {
	const blocking = new Map(PLUGIN.hooks.map((h) => [h.event, h.blocking]));
	const native = (map: HostHookMap, event: LifecycleEvent): string => {
		const hooks = map[event];
		if (hooks.length === 0) return "—";
		return hooks
			.map(
				(h) =>
					`${code(h.event)}${h.matcher === undefined ? "" : ` (matcher ${code(h.matcher)})`}`,
			)
			.join("<br/>");
	};
	const body = [
		"The lifecycle points maina hooks, and the native hook each host registers for them, read from the host adapters' hook maps. A blocking hook gates an action, so when it crashes or times out the action is blocked (fail closed).",
		"",
		"## Lifecycle events",
		"",
		table(
			["Event", "What maina does", "Blocking"],
			LIFECYCLE.map((e) => [
				code(e),
				cell(LIFECYCLE_EVENTS[e]),
				blocking.has(e) ? (blocking.get(e) ? "yes" : "no") : "not hooked",
			]),
		),
		"",
		"## Host mappings",
		"",
		table(
			["Event", ...HOSTS.map((h) => h.name)],
			LIFECYCLE.map((e) => [code(e), ...HOSTS.map((h) => native(h.map, e))]),
		),
	];
	return mdxPage(
		"Hook events reference",
		"The lifecycle events maina hooks and each host's native hooks for them, generated from the adapters.",
		body.join("\n"),
	);
}

// ── Reference: config and policy (from the JSON Schemas) ────────────────────

type Schema = Readonly<{
	type?: string;
	description?: string;
	properties?: Readonly<Record<string, Schema>>;
	additionalProperties?: Schema | boolean;
	propertyNames?: Schema;
	items?: Schema;
	anyOf?: readonly Schema[];
	enum?: readonly unknown[];
	const?: unknown;
	minimum?: number;
	maximum?: number;
}>;

const asSchema = (s: Schema | boolean | undefined): Schema | undefined =>
	typeof s === "object" ? s : undefined;

function typeOf(s: Schema): string {
	if (s.const !== undefined) return code(String(s.const));
	if (s.enum) return s.enum.map((v) => code(String(v))).join(" or ");
	if (s.anyOf) return s.anyOf.map(typeOf).join(" or ");
	if (s.type === "array") {
		return s.items ? `array of ${typeOf(s.items)}` : "array";
	}
	if (s.type === "object") {
		if (s.properties) return "object";
		const value = asSchema(s.additionalProperties);
		return value
			? `map of ${value.properties ? "object" : typeOf(value)}`
			: "object";
	}
	if (s.type === "number" || s.type === "integer") {
		if (s.minimum !== undefined && s.maximum !== undefined) {
			return `${s.type} (${s.minimum} to ${s.maximum})`;
		}
		if (s.minimum !== undefined) return `${s.type} (at least ${s.minimum})`;
	}
	return s.type ?? "any";
}

function schemaRows(
	s: Schema,
	path: string,
	out: (readonly string[])[],
): (readonly string[])[] {
	for (const [key, prop] of Object.entries(s.properties ?? {})) {
		if (key === "$schema") continue;
		const full = path === "" ? key : `${path}.${key}`;
		out.push([code(full), typeOf(prop), cell(prop.description ?? "")]);
		schemaRows(prop, full, out);
		if (prop.items?.properties) schemaRows(prop.items, `${full}[]`, out);
		const value = asSchema(prop.additionalProperties);
		if (value?.properties) {
			const name = prop.propertyNames?.enum ? "<type>" : "<name>";
			schemaRows(value, `${full}.${name}`, out);
		}
	}
	return out;
}

function schemaTable(schema: unknown): string {
	return table(
		["Key", "Type", "Description"],
		schemaRows(schema as Schema, "", []),
	);
}

function renderConfig(): string {
	const body = [
		"Every key `maina.config.*` accepts, read from the zod schema that also generates `schemas/maina.config.schema.json`. Every key is optional.",
		"",
		schemaTable(configJsonSchema()),
	];
	return mdxPage(
		"Config reference",
		"Every maina config key, generated from the config schema.",
		body.join("\n"),
	);
}

function renderPolicy(): string {
	const classes = Object.entries(DEFAULT_POLICY.action_classes).sort(
		([a], [b]) => a.localeCompare(b),
	);
	const body = [
		"Every key a policy file (`.maina/policy.json` in a repo, `~/.maina/policy.json` for the user) accepts, read from the zod schema that also generates `schemas/policy.schema.json`. Layers merge in the order defaults, user, repo.",
		"",
		schemaTable(policyJsonSchema()),
		"",
		"## Built-in action classes",
		"",
		"The default policy's action classes and their verdicts. A locked class cannot be loosened by any policy layer, `explicitly_allow` included.",
		"",
		table(
			["Action class", "Default verdict", "Irreversible", "Locked"],
			classes.map(([id, spec]) => [
				code(id),
				code(spec.verdict),
				spec.irreversible ? "yes" : "no",
				isLockedClass(id) ? "yes" : "no",
			]),
		),
	];
	return mdxPage(
		"Policy reference",
		"Every policy key and built-in action class, generated from the policy schema and defaults.",
		body.join("\n"),
	);
}

// ── Reference: decision types ───────────────────────────────────────────────

function renderDecisionTypes(): string {
	const body = [
		"Every decision type `decide` answers (the `decide` MCP tool and `maina decide`), read from the decision catalog. The policy's `decisions` key picks a type's backend and thresholds; the default backend serves it otherwise.",
		"",
		table(
			["Type", "Question", "Question kinds", "Options", "Default backend"],
			DECISION_TYPES.map((type) => {
				const entry = DECISION_CATALOG[type];
				return [
					code(type),
					cell(entry.description),
					entry.kinds.map((k) => code(k)).join(", "),
					entry.options ? entry.options.map((o) => code(o)).join(", ") : "any",
					code(entry.defaultBackend),
				];
			}),
		),
	];
	return mdxPage(
		"Decision types reference",
		"Every decision type maina's decide answers, generated from the decision catalog.",
		body.join("\n"),
	);
}

// ── Changesets: roadmap and changelog ───────────────────────────────────────

type Bump = "major" | "minor" | "patch";

export type Changeset = Readonly<{
	id: string;
	bumps: Readonly<Record<string, Bump>>;
	summary: string;
}>;

const BUMPS: readonly Bump[] = ["major", "minor", "patch"];

/** A changeset's package bumps and summary. */
export function parseChangeset(text: string): Omit<Changeset, "id"> {
	const match = /^---\r?\n([\s\S]*?)\r?\n?---\r?\n?([\s\S]*)$/.exec(text);
	const front = match?.[1] ?? "";
	const bumps: Record<string, Bump> = {};
	for (const line of front.split(/\r?\n/)) {
		const m = /^\s*["']?([^"':]+)["']?\s*:\s*(major|minor|patch)\s*$/.exec(
			line,
		);
		if (m?.[1] && m[2]) bumps[m[1].trim()] = m[2] as Bump;
	}
	return { bumps, summary: (match?.[2] ?? text).trim() };
}

function readChangesets(root: string): Changeset[] {
	const dir = join(root, ".changeset");
	return listDir(dir)
		.filter((n) => n.endsWith(".md") && n !== "README.md")
		.map((n) => ({
			id: n.replace(/\.md$/, ""),
			...parseChangeset(readFileSync(join(dir, n), "utf-8")),
		}));
}

/** The strongest bump a changeset makes, or undefined for an empty one. */
const topBump = (c: Changeset): Bump | undefined =>
	BUMPS.find((b) => Object.values(c.bumps).includes(b));

/** A sentence ending that is only an abbreviation ("e.g."). */
const ABBREVIATION = /\b(?:e\.g|i\.e|etc|vs|cf)\.$/i;

/** The first sentence of the first paragraph, on one line. */
function firstSentence(summary: string): string {
	const para = (summary.split(/\n\s*\n/)[0] ?? "").replace(/\s*\n\s*/g, " ");
	for (const m of para.matchAll(/[.!?](?=\s+\S)/g)) {
		const sentence = para.slice(0, m.index + 1);
		if (!ABBREVIATION.test(sentence)) return sentence;
	}
	return para;
}

const GROUP_TITLES: Readonly<Record<Bump, string>> = {
	major: "Breaking changes",
	minor: "Features",
	patch: "Fixes",
};

export function renderRoadmap(
	changesets: readonly Changeset[],
	versions: Readonly<Record<string, string>>,
): string {
	const sorted = [...changesets].sort((a, b) => a.id.localeCompare(b.id));
	const groups = BUMPS.map((bump) => {
		const items = sorted.filter((c) => topBump(c) === bump);
		if (items.length === 0) return "";
		return [
			`### ${GROUP_TITLES[bump]}`,
			"",
			...items.map(
				(c) =>
					`- ${escapeText(firstSentence(c.summary))} _(${Object.keys(c.bumps).sort().join(", ")})_`,
			),
			"",
		].join("\n");
	}).filter((g) => g !== "");
	const body = [
		"What is released, and what the next release brings. The next release is read from the pending changesets: every merged change records one, and each lands in the next version of the packages it names. The full notes are in the [changelog](/changelog/).",
		"",
		"## Released",
		"",
		table(
			["Package", "Version"],
			Object.entries(versions)
				.sort(([a], [b]) => a.localeCompare(b))
				.map(([name, version]) => [code(name), code(version)]),
		),
		"",
		"## Next release",
		"",
		groups.length === 0 ? "No changes are pending." : groups.join("\n"),
		"",
		"## Contributing",
		"",
		"Maina is open source and welcomes contributions: see [CONTRIBUTING.md](https://github.com/mainahq/maina/blob/master/CONTRIBUTING.md). Every change carries a changeset (`bun run changeset`), and this page is generated from them.",
	];
	return mdxPage(
		"Roadmap",
		"What is released and what the next release brings, generated from the changesets.",
		body.join("\n"),
	);
}

/** A CHANGELOG.md body, its headings one level down, its title dropped. */
function demote(changelog: string): string {
	let fenced = false;
	return changelog
		.split("\n")
		.filter((line, i) => !(i === 0 && /^# /.test(line)))
		.map((line) => {
			if (/^\s*(`{3,}|~{3,})/.test(line)) fenced = !fenced;
			return !fenced && /^#{1,5} /.test(line) ? `#${line}` : line;
		})
		.join("\n")
		.trim();
}

const indent = (text: string, by: string): string =>
	text
		.split("\n")
		.map((l, i) => (i === 0 || l === "" ? l : `${by}${l}`))
		.join("\n");

function renderChangelog(
	root: string,
	changesets: readonly Changeset[],
	versions: Readonly<Record<string, string>>,
): string {
	const sorted = [...changesets].sort((a, b) => a.id.localeCompare(b.id));
	const sections = Object.keys(versions)
		.sort()
		.map((name) => {
			const dir = name.replace(/^@mainahq\//, "");
			const pending = BUMPS.map((bump) => {
				const items = sorted.filter((c) => c.bumps[name] === bump);
				if (items.length === 0) return "";
				const title = `${bump[0]?.toUpperCase()}${bump.slice(1)} Changes`;
				return [
					`#### ${title}`,
					"",
					...items.map((c) => `- ${indent(c.summary, "  ")}`),
					"",
				].join("\n");
			}).filter((s) => s !== "");
			// A package with no release yet has no changelog.
			const released = demote(
				readOrEmpty(join(root, "packages", dir, "CHANGELOG.md")),
			);
			return [
				`## ${name}`,
				"",
				"### Unreleased",
				"",
				pending.length === 0 ? "No changes are pending." : pending.join("\n"),
				"",
				released,
				"",
			].join("\n");
		});
	const body = [
		"Every change to the published packages, from the changesets: the pending ones under Unreleased, then each released version's notes.",
		"",
		escapeMarkdown(sections.join("\n")),
	];
	return mdxPage(
		"Changelog",
		"Every change to maina's published packages, generated from the changesets.",
		body.join("\n"),
	);
}

// ── Generation ──────────────────────────────────────────────────────────────

/** Every generated file under `root`, by repo-relative path, in a fixed order. */
export function generateDocs(root: string): ReadonlyMap<string, string> {
	const facts = collectFacts(root);
	const changesets = readChangesets(root);
	const out = new Map<string, string>([
		[FACTS_FILE, renderFactsModule(facts)],
		[`${DOCS}/reference/commands.mdx`, renderCommands(cliCommands())],
		[`${DOCS}/reference/mcp-tools.mdx`, renderMcpTools()],
		[`${DOCS}/reference/hooks.mdx`, renderHooks()],
		[`${DOCS}/reference/config.mdx`, renderConfig()],
		[`${DOCS}/reference/policy.mdx`, renderPolicy()],
		[`${DOCS}/reference/decision-types.mdx`, renderDecisionTypes()],
		[`${DOCS}/roadmap.mdx`, renderRoadmap(changesets, facts.packages)],
		[
			`${DOCS}/changelog.mdx`,
			renderChangelog(root, changesets, facts.packages),
		],
	]);
	return out;
}

function readOrEmpty(path: string): string {
	try {
		return readFileSync(path, "utf-8");
	} catch {
		return "";
	}
}

/** Generated files under `root` whose committed bytes differ. */
export function staleDocs(root: string): string[] {
	return [...generateDocs(root)]
		.filter(([path, text]) => readOrEmpty(join(root, path)) !== text)
		.map(([path]) => path);
}

// ── Hand-written check ──────────────────────────────────────────────────────

export type Hit = Readonly<{
	line: number;
	kind: "count" | "version" | "tool" | "command";
	match: string;
}>;

const IGNORE =
	/<!--\s*docs-manifest:\s*ignore\s*-->|\{\/\*\s*docs-manifest:\s*ignore\s*\*\/\}/i;

const COUNT =
	/\b\d+\s+(?:commands|MCP tools|tools|skills|decision types|hook events|lifecycle events|hosts)\b/gi;

/** A semver (optionally `v`-prefixed) that is not part of a dotted quad. */
const VERSION_LITERAL = /(?<![\d.])v?(\d+\.\d+\.\d+)(?!\d|\.\d)/g;

/** `name` MCP tool / `name` tool, where the name looks like an MCP tool. */
const TOOL_MENTION = /`([a-z][a-z0-9_]*)`\s+(?:MCP\s+)?tool\b/g;

/** `maina <cmd>` in inline code. */
const INLINE_COMMAND = /`maina ([a-z][a-z0-9-]*)/g;

/** A shell line in a fenced block that runs `maina <cmd>`. */
const FENCED_COMMAND = /^\s*(?:\$\s+)?maina ([a-z][a-z0-9-]*)/;

/**
 * Counts, versions, MCP tool names and maina commands a hand-written page
 * states that are not taken from `facts`. Values interpolated from facts.ts
 * (`{facts.version}`) never match: they are not literals in the source.
 */
export function scanHandWritten(text: string, facts: Facts): Hit[] {
	const tools = new Set(facts.mcpTools.all);
	const commands = new Set([
		...facts.commands.names,
		...facts.commands.internal,
	]);
	const hits: Hit[] = [];
	const lines = text.split(/\r?\n/);
	// The open fence's marker: only a fence of the same character, at least
	// as long, closes it (as in escapeMarkdown).
	let fence: string | null = null;
	lines.forEach((line, i) => {
		const marker = /^\s*(`{3,}|~{3,})/.exec(line)?.[1];
		const opens = fence === null && marker !== undefined;
		const closes = fence !== null && marker?.startsWith(fence) === true;
		const isFence = opens || closes;
		if (opens) fence = marker;
		const fenced = fence !== null;
		if (closes) fence = null;
		if (IGNORE.test(line) || (i > 0 && IGNORE.test(lines[i - 1] ?? ""))) {
			return;
		}
		const add = (kind: Hit["kind"], match: string) =>
			hits.push({ line: i + 1, kind, match });
		for (const m of line.matchAll(COUNT)) add("count", m[0]);
		for (const m of line.matchAll(VERSION_LITERAL)) add("version", m[1] ?? "");
		for (const m of line.matchAll(TOOL_MENTION)) {
			if (m[1] && !tools.has(m[1])) add("tool", m[1]);
		}
		const cmds =
			fenced && !isFence
				? [FENCED_COMMAND.exec(line)?.[1]]
				: [...line.matchAll(INLINE_COMMAND)].map((m) => m[1]);
		for (const cmd of cmds) {
			if (cmd && !commands.has(cmd)) add("command", `maina ${cmd}`);
		}
	});
	return hits;
}

function walkPages(dir: string): string[] {
	return listDir(dir).flatMap((name) => {
		const full = join(dir, name);
		try {
			if (statSync(full).isDirectory()) return walkPages(full);
		} catch {
			return [];
		}
		return name.endsWith(".md") || name.endsWith(".mdx") ? [full] : [];
	});
}

export type FileHit = Hit & Readonly<{ file: string }>;

/** Hits in README.md and the docs site's hand-written pages under `root`. */
export function checkHandWrittenDocs(root: string, facts: Facts): FileHit[] {
	const generated = new Set(GENERATED_DOCS);
	const files = [join(root, "README.md"), ...walkPages(join(root, DOCS))];
	return files.flatMap((file) => {
		const rel = relative(root, file).split(sep).join("/");
		if (generated.has(rel)) return [];
		const text = readOrEmpty(file);
		return scanHandWritten(text, facts).map((hit) => ({ file: rel, ...hit }));
	});
}

// ── Entrypoint ──────────────────────────────────────────────────────────────

const out = (line: string): void => {
	process.stdout.write(`${line}\n`);
};
const err = (line: string): void => {
	process.stderr.write(`${line}\n`);
};

const HINTS: Readonly<Record<Hit["kind"], string>> = {
	count: "import facts and write {facts.<registry>.count}",
	version: "import facts and write {facts.version}",
	tool: "name only tools in facts.mcpTools",
	command: "name only commands the CLI registers",
};

function runCheck(): number {
	const facts = collectFacts(ROOT);
	const stale = staleDocs(ROOT);
	const hits = checkHandWrittenDocs(ROOT, facts);
	if (stale.length === 0 && hits.length === 0) {
		out(
			"docs-manifest --check: OK: generated docs are current and hand-written pages take their facts from facts.ts.",
		);
		return 0;
	}
	err("docs-manifest --check: FAIL");
	for (const path of stale) {
		err(`  ${path}: stale; run \`bun run docs:generate\``);
	}
	for (const h of hits) {
		err(
			`  ${h.file}:${h.line}: hand-written ${h.kind} "${h.match}"; ${HINTS[h.kind]}`,
		);
	}
	err(
		"\nA line that must keep a literal (a historical note) can carry a `docs-manifest: ignore` comment.",
	);
	return 1;
}

function writeDocs(): void {
	for (const [path, text] of generateDocs(ROOT)) {
		const full = join(ROOT, path);
		if (readOrEmpty(full) === text) continue;
		mkdirSync(dirname(full), { recursive: true });
		writeFileSync(full, text);
		out(`wrote ${path}`);
	}
}

function main(): number {
	const args = process.argv.slice(2);
	if (args.includes("--check")) return runCheck();
	if (args.includes("--json")) {
		out(JSON.stringify(collectFacts(ROOT), null, 2));
		return 0;
	}
	writeDocs();
	return 0;
}

if (import.meta.main) {
	process.exit(main());
}
