#!/usr/bin/env bun
/**
 * Single version source (#294, FR-INS-2).
 *
 * Generates `packages/core/src/version.ts` from the version `changeset
 * version` writes into `packages/core/package.json`. `VERSION`, exported
 * from `@mainahq/core`, is the only place the runtime reads its version;
 * cli, core and mcp are one `fixed` changesets group, so they always share it.
 *
 *     bun scripts/version-source.ts           # (re)write the module
 *     bun scripts/version-source.ts --check   # exit 1 when it is stale
 *
 * `bun run version` (what the release workflow runs) calls this right after
 * `changeset version`.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

type Result<T, E = string> =
	| { readonly ok: true; readonly value: T }
	| { readonly ok: false; readonly error: E };

export const VERSION_MODULE = "packages/core/src/version.ts";
const MANIFEST = "packages/core/package.json";

/**
 * semver 2.0: MAJOR.MINOR.PATCH, optional -prerelease and +build. Numeric
 * prerelease identifiers have no leading zeros (§9); build ones may.
 */
const PRERELEASE_ID = "(?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*)";
const SEMVER = new RegExp(
	`^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-${PRERELEASE_ID}(\\.${PRERELEASE_ID})*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$`,
);

export function renderVersionModule(version: string): Result<string> {
	if (!SEMVER.test(version)) {
		return {
			ok: false,
			error: `not a semver version: ${JSON.stringify(version)}`,
		};
	}
	return {
		ok: true,
		value: [
			"// Generated by scripts/version-source.ts from packages/core/package.json.",
			"// Do not edit: `bun run version` regenerates it after `changeset version`.",
			"",
			"/** The maina version. The only place the runtime reads it from. */",
			`export const VERSION = "${version}";`,
			"",
		].join("\n"),
	};
}

export function versionFromManifest(raw: string): Result<string> {
	try {
		const parsed = JSON.parse(raw) as { version?: unknown };
		return typeof parsed.version === "string"
			? { ok: true, value: parsed.version }
			: { ok: false, error: "manifest has no version" };
	} catch (e) {
		return { ok: false, error: e instanceof Error ? e.message : String(e) };
	}
}

/** `current` is the module on disk, or null when it does not exist. */
export function checkVersionModule(
	current: string | null,
	version: string,
): Result<void> {
	const expected = renderVersionModule(version);
	if (!expected.ok) return expected;
	if (current === expected.value) return { ok: true, value: undefined };
	return {
		ok: false,
		error: `${VERSION_MODULE} is ${current === null ? "missing" : "stale"}; run \`bun scripts/version-source.ts\``,
	};
}

function main(argv: readonly string[]): number {
	const root = resolve(import.meta.dir, "..");
	const version = versionFromManifest(
		readFileSync(join(root, MANIFEST), "utf-8"),
	);
	if (!version.ok) {
		process.stderr.write(`${MANIFEST}: ${version.error}\n`);
		return 1;
	}
	const target = join(root, VERSION_MODULE);
	if (argv.includes("--check")) {
		const current = existsSync(target) ? readFileSync(target, "utf-8") : null;
		const check = checkVersionModule(current, version.value);
		if (check.ok) return 0;
		process.stderr.write(`${check.error}\n`);
		return 1;
	}
	const module = renderVersionModule(version.value);
	if (!module.ok) {
		process.stderr.write(`${MANIFEST}: ${module.error}\n`);
		return 1;
	}
	writeFileSync(target, module.value);
	return 0;
}

if (import.meta.main) {
	process.exit(main(process.argv.slice(2)));
}
